import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation objects
const translations = {
  al: {
    // Navigation
    home: 'Kryefaqja',
    listings: 'Pronat',
    buy: 'Bli',
    rent: 'Qera',
    addListing: 'Posto Pronë',
    profile: 'Profili',
    login: 'Kyçu',
    logout: 'Dil',
    contact: 'Kontakto',
    favorites: 'Të preferuarat',
    admin: 'Admin',
    partnerships: 'Partneritete',

    // Partnerships page
    partnershipsHeroTitle: 'Partneri me',
    partnershipsHeroSubtitle: 'Bashkohuni me platformën kryesore të pasurive të paluajtshme në Shqipëri. Së bashku, mund të ndërtojmë të ardhmen e pronave.',
    becomePartner: 'Bëhu Partner',
    globalReach: 'Arritje Globale',
    globalReachDesc: 'Hyni në rrjetin tonë botëror të investuesve dhe kërkuesve të pronave.',
    premiumBranding: 'Branding Premium',
    premiumBrandingDesc: 'Harmonizo biznesin tënd me platformën tonë të besueshme dhe të nivelit të lartë të pasurive të paluajtshme.',
    growthSupport: 'Mbështetje për Rritje',
    growthSupportDesc: 'Ekip mbështetjeje i dedikuar për të të ndihmuar të maksimizosh potencialin e partneritetit.',
    readyToGrow: 'Gati për të rritur me ne?',
    readyToGrowDesc: 'Le të diskutojmë se si mund të krijojmë vlerë së bashku. Kontaktoni ekipin tonë të partneriteteve sot.',

    // Home page
    heroTitle: 'Gjej Shtëpinë e Ëndrrave',
    heroSubtitle: 'Zbulo prona premium, lidhu me agjentë të besueshëm dhe gjej vendin e përsosur për të quajtur shtëpi.',
    searchPlaceholder: 'Kërko prona në Shqipëri...',
    searchButton: 'Kërko',
    whatAreYouLookingFor: 'Çfarë po kërkoni?',
    selectPropertyPurpose: 'Zgjidhni nëse dëshironi të blini apo të merrni me qera',
    buyProperty: 'Bli Pronë',
    rentProperty: 'Merr me Qera',
    cancel: 'Anulo',
    featuredListings: 'PRONA TË PROMOVUARA',
    promotedProperties: 'Prona të Promovuara',
    promotedPropertiesDesc: 'Prona të promovuara nga pronarët për dukshmëri maksimale',
    noFeaturedProperties: 'Ende Nuk Ka Prona të Promovuara',
    noFeaturedPropertiesDesc: 'Pronarët e pronave mund të promovojnë listat e tyre falas për të shfaqur këtu!',

    // Home page stats and sections
    trustedPlatform: 'Platforma e Besueshme në Shqipëri',
    properties: 'Prona',
    happyClients: 'Klientë të Kënaqur',
    expertAgents: 'Agjentë Ekspertë',
    viewDetails: 'Shiko Detajet',
    viewAllProperties: 'Shiko të Gjitha Pronat',
    whyChooseUs: 'Pse Na Zgjidhni Ne?',
    whyChooseUsSubtitle: 'Partneri juaj i besuar për gjetjen e pronës së përsosur',
    verifiedListings: 'Postime të Verifikuara',
    verifiedListingsDesc: 'Të gjitha postimet janë verifikuar dhe kontrolluar nga ekipi ynë për cilësi të garantuar.',
    expertAgentsTitle: 'Agjentë Ekspertë',
    expertAgentsDesc: 'Lidhuni me profesionistë me eksperiencë të pasurive të paluajtshme që njohin tregun.',
    fastAndEasy: 'Shpejt dhe e Lehtë',
    fastAndEasyDesc: 'Gjeni shtëpinë tuaj të ëndrrave shpejt me mjetet tona të avancuara të kërkimit dhe filtrimit.',

    // Property details
    forSale: 'Për Shitje',
    forRent: 'Për Qera',
    featured: 'TË PROMOVUARA',
    rooms: 'dhoma',
    bathrooms: 'banjo',
    size: 'm²',
    contactOwner: 'Kontakto rin',
    viewOnMap: 'Shiko në Hartë',
    description: 'Përshkrimi',
    location: 'Vendndodhja',
    price: 'Çmimi',
    type: 'Lloji',
    addToFavorites: 'Shto në të Preferuarat',
    removeFromFavorites: 'Hiq nga të Preferuarat',

    // Profile page
    profileTitle: 'Profili im',
    myListings: 'Pronat e mia',
    noListings: 'Ende nuk ka lista',
    noListingsDesc: 'Fillo të shtosh prona për t\'i shfaqur këtu',
    editListing: 'Ndrysho',
    deleteListing: 'Fshi',
    promoteForFree: '🚀 Promovo FALAS (14 ditë)',
    featuredListing: '✅ Pronë e Promovuar',
    views: 'shikime',
    profileInformation: 'Informacioni i Profilit',
    edit: 'Ndrysho',
    email: 'Email',
    phone: 'Telefon',
    firstName: 'Emri',
    lastName: 'Mbiemri',
    saveChanges: 'Ruaj Ndryshimet',
    cancel: 'Anulo',
    deleteAccount: 'Fshi Llogarinë',
    deleteAccountWarning: 'Pasi të fshish llogarinë, nuk ka kthim prapa. Ju lutemi jini të sigurt.',
    deleteAccountPermanently: 'Fshi Llogarinë Time Përgjithmonë',
    logOut: 'Dil',
    user: 'Përdorues',
    agent: 'Agjent',

    // Boost Success Modal
    successTitle: 'Sukses!',
    listingBoosted: 'Prona u Promovua!',
    boostSuccessMessage: 'Prona juaj u promovua me sukses për 15 ditë',
    premiumVisibility: 'Dukshmëri Premium',
    boostActiveMessage: 'Prona juaj tani do të shfaqet në krye të rezultateve të kërkimit',
    refreshingPage: 'Duke rifreskuar faqen...',

    // Mark as Sold
    markAsSold: 'Shëno si e Shitur',
    markAsSoldTitle: 'Shëno si e Shitur?',
    markAsSoldConfirm: 'Kjo do të regjistrojë shitjen në statistikat tuaja dhe do ta heqë postimin nga platforma. Ky veprim nuk mund të zhbëhet.',
    confirmSold: 'Po, Shëno si e Shitur',
    congratulations: 'Urime!',
    propertySold: 'Prona u Shit me Sukses!',
    saleRecorded: '🏆 Shitja u Regjistrua!',
    congratsMessage: 'Shitja juaj është regjistruar në statistikat tuaja. Postimi është hequr nga platforma.',
    thankYou: 'Faleminderit që përdorni platformën tonë!',
    keepUpSuccess: 'Vazhdoni punën e shkëlqyer! 🚀',
    markSoldError: 'Dështoi shënimi si e shitur. Ju lutemi provoni përsëri.',

    editListingTitle: 'Ndrysho Listën',
    title: 'Titulli',
    currentImages: 'Imazhet Aktuale',
    newImages: 'Imazhe të Reja',
    addMoreImages: 'Shto Më Shumë Imazhe',
    youCanSelectMultiple: 'Mund të zgjidhni shumë imazhe njëkohësisht',
    expiresSoon: 'Skadon së shpejti',
    daysLeft: 'ditë të mbetura',
    pleaseLogInToViewProfile: 'Ju lutem hyni në llogari për të parë profilin tuaj.',
    loadingProfile: 'Duke ngarkuar profilin...',
    changePassword: 'Ndrysho Fjalëkalimin',
    currentPassword: 'Fjalëkalimi Aktual',
    newPassword: 'Fjalëkalimi i Ri',
    confirmNewPassword: 'Konfirmo Fjalëkalimin e Ri',
    enterCurrentPassword: 'Shkruani fjalëkalimin aktual',
    enterNewPassword: 'Shkruani fjalëkalimin e ri',
    passwordMinLength: 'Fjalëkalimi duhet të jetë të paktën 6 karaktere',
    updatingPassword: 'Duke përditësuar fjalëkalimin...',
    passwordChangedSuccess: 'Fjalëkalimi u ndryshua me sukses!',
    wrongCurrentPassword: 'Fjalëkalimi aktual është i gabuar.',
    cannotChangePasswordGoogle: 'Ju jeni kyçur me Google. Ndryshimi i fjalëkalimit nuk është i mundur për llogaritë Google.',
    pleaseLoginAgain: 'Ju lutemi dilni dhe hyni përsëri para se të ndryshoni fjalëkalimin tuaj.',
    passwordChangeInfo: 'Fjalëkalimi juaj i ri duhet të jetë të paktën 6 karaktere dhe të ndryshojë nga fjalëkalimi aktual.',
    promoteYourListing: '🚀 Promovo Pronën Tënde',
    getMaxVisibility: 'Merrni dukshmëri maksimale dhe tërhiqni më shumë blerës - plotësisht FALAS!',
    featuredListingPlan: '⭐ Postime e Veçantë',
    promoteProperty14Days: 'Promovoni pronën tuaj për 14 ditë pa pagesë',
    freeLabel: 'FALAS',
    days14: '14 ditë',
    featuredOnHomepage: 'E veçantë në faqen kryesore për dukshmëri maksimale',
    topOfSearchResults: 'Në krye të rezultateve të kërkimit në të gjitha kategoritë',
    specialFeaturedBadge: 'Shenjë speciale e veçantë në postimin tuaj',
    days14Premium: '14 ditë vendosje premium',
    increasedViews: 'Rritje e shikimeve dhe angazhimit',
    promotingListing: 'Duke promovuar postimin...',
    completelyFree: 'Plotësisht Falas:',
    noPaymentRequired: 'Nuk kërkohet pagesë! Postimi juaj do të promovohet automatikisht për 14 ditë dhe do të shfaqet në krye të rezultateve të kërkimit.',

    // ListingPage translations
    exploreProperties: 'Eksploroni Pronat',
    findPerfectHome: 'Gjeni shtëpinë tuaj të përsosur nga {count} postimet e disponueshme',
    search: 'Kërkoni',
    searchPlaceholder: 'Kërkoni sipas titullit ose vendndodhjes...',
    type: 'Lloji',
    all: 'Të gjitha',
    buy: 'Bli',
    rent: 'Qera',
    propertyType: 'Lloji i Pronës',
    allTypes: 'Të gjitha Llojet',
    apartment: 'Apartament',
    privateHome: 'Shtëpi Private',
    land: 'Tokë',
    business: 'Ambient Biznesi',
    priceRange: 'Gama e çmimeve',
    features: 'Veçoritë',
    clearAll: 'Pastro të gjitha',
    min: 'Min',
    max: 'Maks',
    loadingProperties: 'Duke ngarkuar pronat...',
    pleaseWaitFetching: 'Ju lutem prisni derisa të marrim postimet',
    updatingMap: 'Duke përditësuar hartën...',
    filteringResults: 'Duke filtruar rezultatet...',
    noPropertiesFound: 'Nuk u gjetën prona',
    adjustFilters: 'Provoni të ndryshoni filtrat për të parë më shumë rezultate',
    forRent: 'Për Qera',
    forSale: 'Për Shitje',
    featured: 'Premium',
    showMap: 'Shfaq Hartën',
    showListings: 'Shfaq Pronat',

    // ListingMain translations
    loading: 'Duke ngarkuar...',
    fullView: 'Pamje e plotë',
    bedrooms: 'Dhoma gjumi',
    bathrooms: 'Banjo',
    propertySize: 'Madhësia e Pronës',
    location: 'Vendndodhja',
    listingId: 'ID e Listës',
    notSpecified: 'Nuk është specifikuar',
    description: 'Përshkrimi',
    propertyDetails: 'Detajet e Pronës',
    listedBy: 'Postuar nga',
    realEstateAgent: 'Agjent Pasurie',
    agency: 'Agjensi',
    privateSeller: 'Shitës Privat',
    email: 'Email',
    phone: 'Telefon',
    callNow: 'Telefono Tani',
    sendEmail: 'Dërgo Email',
    calculateMortgage: 'Llogarit Kredinë',
    hideMortgage: 'Fshih Kredinë',
    mortgageCalculatorTitle: 'Llogaritësi i Kredisë',
    estimateMonthlyPayment: 'Vlerëso pagesën mujore',
    estimatedMonthlyPayment: 'Pagesa Mujore e Vlerësuar',
    principalAndInterest: 'Kryesorja & Interesi',
    propertyPrice: 'Çmimi i Pronës',
    downPayment: 'Pagesa Fillestare',
    interestRate: 'Norma e Interesit',
    loanTerm: 'Kohëzgjatja e Kredisë',
    years: 'vjet',
    loanAmount: 'Shuma e Kredisë',
    totalPayment: 'Pagesa Totale',
    totalInterest: 'Interesi Total',
    mortgageDisclaimer: '* Ky është një vlerësim. Pagesat aktuale mund të ndryshojnë bazuar në taksa, sigurime dhe faktorë të tjerë.',
    shareProperty: 'Ndaj këtë pronë',
    removeFromFavorites: 'Hiq nga të preferuarat',
    addToFavorites: 'Shto në të preferuarat',
    perMonth: 'në muaj',
    listedOnPlatform: 'Postuar në këtë platformë',

    // WhatsApp Messages
    whatsappMessageToSeller: 'Përshëndetje! Jam i interesuar për pronën tuaj: {title} - €{price}\n\nShiko këtu: {link}',
    whatsappShareMessage: 'Shiko këtë pronë: {title} - €{price} {link}',

    // Time ago translations
    postedAgo: 'Postuar',
    justNow: 'Tani',
    oneMinuteAgo: '1 minutë më parë',
    minutesAgo: 'minuta më parë',
    oneHourAgo: '1 orë më parë',
    hoursAgo: 'orë më parë',
    oneDayAgo: '1 ditë më parë',
    daysAgo: 'ditë më parë',
    oneWeekAgo: '1 javë më parë',
    weeksAgo: 'javë më parë',
    oneMonthAgo: '1 muaj më parë',
    monthsAgo: 'muaj më parë',
    oneYearAgo: '1 vit më parë',
    yearsAgo: 'vite më parë',

    // Map translations
    exactLocation: 'Vendndodhja e Perafert',
    staticMapInfo: 'Kjo hartë tregon vendndodhjen e përafërt të pronës',
    openInMaps: 'Hap në Hartat',
    clickToOpenMaps: 'Kliko për të hapur në Google Maps për drejtim',

    // Contact page translations
    wereHereToHelp: 'Jemi Këtu për ju Ndihmuar',
    getInTouch: 'Kontaktoni me Ne',
    contactPageSubtitle: 'Keni një pyetje ose keni nevojë për ndihmë? Ekipi ynë është gati t\'ju ndihmojë të gjeni pronën e ëndrrave tuaja.',
    callUs: 'Na Telefononi',
    emailUs: 'Na Dërgoni Email',
    visitUs: 'Na Vizitoni',
    mondayToFriday: 'Hën-Pre nga 08:00 deri 18:00',
    emailResponse: 'Do t\'ju përgjigjemi brenda 24 orëve',
    comeVisitOffice: 'Ejani të na thoni përshëndetje në zyrën tonë',
    sendUsMessage: 'Na Dërgoni një Mesazh',
    formSubtitle: 'Plotësoni formularin më poshtë dhe ne do t\'ju kontaktojmë sa më shpejt të jetë e mundur.',
    thankYouMessage: 'Faleminderit! Mesazhi juaj u dërgua me sukses.',
    fullName: 'Emri i Plotë',
    emailAddress: 'Adresa Email',
    phoneNumber: 'Numri i Telefonit',
    subject: 'Tema',
    selectSubject: 'Zgjidhni një temë',
    generalInquiry: 'Pyetje e Përgjithshme',
    buyingProperty: 'Blerje Prone',
    sellingProperty: 'Shitje Prone',
    rentingProperty: 'Prone me Qera',
    technicalSupport: 'Mbështetje Teknike',
    other: 'Tjetër',
    message: 'Mesazhi',
    messagePlaceholder: 'Na tregoni si mund t\'ju ndihmojmë...',
    sendMessage: 'Dërgo Mesazhin',
    officeHours: 'Orari i Zyrës',
    mondayFriday: 'E Hënë - E Premte',
    saturday: 'E Shtunë',
    sunday: 'E Diel',
    closed: 'Mbyllur',
    commonQuestions: 'Pyetje të Shpeshta',
    howToListProperty: 'Si të postoj pronën time?',
    listingFees: 'Cilat janë tarifat e postimit?',
    howBoostingWorks: 'Si funksionon promovimi?',
    officeLocationMap: 'Harta e Vendndodhjes së Zyrës',

    // FAQ Pages - How to List Property
    backToContact: 'Kthehu te Kontakti',
    howToListTitle: 'Si të Postoj Pronën Time',
    howToListSubtitle: 'Ndiqni këto hapa të thjeshtë për të postuar pronën tuaj në platformën tonë',
    stepAccount: 'Krijo një Llogari',
    stepAccountDesc: 'Regjistrohu duke përdorur email ose Google. Është e shpejtë, e lehtë dhe plotësisht falas.',
    stepClickAdd: 'Kliko "Posto Pronë"',
    stepClickAddDesc: 'Gjeni butonin në krye të faqes. Duhet të jeni kyçur për të shtuar prona.',
    stepFillDetails: 'Plotëso Detajet',
    stepFillDetailsDesc: 'Shtoni titullin, përshkrimin, çmimin, llojin (Për Shitje/Qera), numrin e dhomave dhe bannave.',
    stepUploadPhotos: 'Ngarko Fotot',
    stepUploadPhotosDesc: 'Shtoni deri në 10 foto cilësore të pronës tuaj. Fotot e mira tërheqin më shumë blerës!',
    stepAddLocation: 'Shto Vendndodhjen',
    stepAddLocationDesc: 'Përdorni formatin: Qyteti, Rruga (p.sh., Tiranë, Rruga Qemal Stafa). Vendodhja duhet të jetë e saktë.',
    stepSubmit: 'Dërgo dhe Publiko',
    stepSubmitDesc: 'Rishikoni të gjitha detajet dhe shtypni Dërgo. Prona juaj do të jetë e dukshme menjëherë!',
    quickTips: 'Këshilla të Shpejta',
    tipQuality: 'Përdorni foto me cilësi të lartë',
    tipHonest: 'Jini të sinqertë me përshkrimin dhe çmimin',
    tipRespond: 'Përgjigjuni shpejt tek interesuarit',
    tipUpdate: 'Mbani postimin të përditësuar',
    readyToList: 'Gati për të Postuar Pronën Tuaj?',
    startListingNow: 'Fillo të Postosh Tani',

    // FAQ Pages - Listing Fees
    listingFeesTitle: 'Tarifat e Postimit',
    listingFeesSubtitle: 'Çmime transparente. Zero Komision.',
    freeListingTitle: 'Postim Bazë FALAS',
    freeListingSubtitle: 'Postime Falas Përgjithmonë',
    freeFeature1: 'Postime të Pakufizuara',
    freeFeature2: 'Deri në 10 Foto për Pronë',
    freeFeature3: 'Afishohet në të Gjitha Kërkimet',
    freeFeature4: 'Formularë Kontakti',
    freeFeature5: 'Asnjë Limitim Kohor',
    freeFeature6: '0% Komision',
    freeFeature7: 'Asnjë Tarifë e Fshehur',
    premiumBoostTitle: 'Promovim Premium',
    premiumBoostSubtitle: '€5 për 15 Ditë',
    premiumFeature1: 'Shenjë e Promovuar',
    premiumFeature2: 'Pozicion në Krye',
    premiumFeature3: 'Prioritet në Faqen Kryesore',
    premiumFeature4: '5x Më Shumë Shikime',
    premiumFeature5: 'Aktivizim i Menjëhershëm',
    premiumFeature6: '15 Ditë Aktiv',
    noCommissionNote: 'Asnjë komision nuk merret për shitjet. Ju mbani 100% të fitimit tuaj!',
    getStartedFree: 'Filloni Falas',

    // FAQ Pages - How Boosting Works
    howBoostingTitle: 'Si Funksionon Promovimi',
    howBoostingSubtitle: 'Rritni dukshmërinë e pronës suaj me promovimin premium',
    whatIsBoost: 'Çfarë është Promovimi?',
    whatIsBoostDesc: 'Promovimi e vendos pronën tuaj në krye të rezultateve të kërkimit dhe në faqen kryesore, duke siguruar dukshmëri maksimale tek blerësit potencialë. Prona juaj do të shfaqet me një shenjë speciale dhe do të marrë 5 herë më shumë shikime.',
    benefit1Title: 'Shenjë e Promovuar',
    benefit1Desc: 'Veçohuni me një shenjë speciale',
    benefit2Title: 'Pozicion në Krye',
    benefit2Desc: 'Shfaqet në krye të kërkimeve',
    benefit3Title: 'Prioritet në Kryefaqe',
    benefit3Desc: 'Shfaqet në seksionin e promovuar',
    benefit4Title: '5x Më Shumë Shikime',
    benefit4Desc: 'Rritni dukshmërinë dramatikisht',
    benefit5Title: 'Aktivizim i Menjëhershëm',
    benefit5Desc: 'Fillon menjëherë pas pagesës',
    benefit6Title: '15 Ditë Aktiv',
    benefit6Desc: 'Mbulim i plotë për 2 javë',
    howToBoostTitle: 'Si të Promovoni Pronën Tuaj',
    howToStep1: 'Shkoni te profili juaj dhe gjeni pronën që dëshironi të promovoni',
    howToStep2: 'Klikoni butonin "Promovo Pronën"',
    howToStep3: 'Zgjidhni PayPal si metodë pagese dhe konfirmoni €5',
    howToStep4: 'Prona juaj promovohet menjëherë pas pagesës së suksesshme!',
    pricingTitle: 'Çmimi dhe Rinovimi',
    pricingDesc: 'Promovimi kushton €5 për 15 ditë. Pas skadimit, prona juaj kthehet në postim normal. Ju mund ta ripromovoni në çdo kohë!',
    boostYourProperty: 'Promovo Pronën Tënde',

    // AddListing page translations
    addNewListing: 'Shto Postim të Ri',
    listingType: 'Lloji i Postimit',
    forSale: 'Për Shitje',
    forRent: 'Për Qera',
    propertyTitle: 'Titulli i Pronës',
    locationPlaceholder: 'Vendndodhja (p.sh., Tirane, Rruga Qemal Stafa)',
    locationHint: 'Përdorni formatin: Qyteti, Rruga (p.sh., Rruga Qemal Stafa)',
    locationFormatError: 'Ju lutem përdorni formatin: Qyteti, Rruga (p.sh., Rruga Qemal Stafa)',
    locationNotGeocoded: 'Ju lutem prisni që vendndodhja të verifikohet ose përdorni një format tjetër',
    geocoding: 'Duke gjetur koordinatat...',
    pricePlaceholder: 'Çmimi (€)',
    selectPropertyType: 'Zgjidhni Llojin e Pronës',
    sizePlaceholder: 'Madhësia (m²)',
    roomsPlaceholder: 'Dhoma',
    bathroomsPlaceholder: 'Banjo',
    descriptionPlaceholder: 'Përshkrimi',
    // New apartment/house features
    additionalFeatures: 'Veçori Shtesë',
    floor: 'Kati',
    floorPlaceholder: 'Kati (p.sh., 3)',
    totalFloors: 'Katet Totale',
    totalFloorsPlaceholder: 'Katet Totale (p.sh., 5)',
    hasElevator: 'Ka Ashensor',
    hasParking: 'Ka Parking',
    hasGarage: 'Ka Garazh',
    hasBalcony: 'Ka Ballkon',
    uploadImages: 'Ngarko Imazhe (Shumë imazhe)',
    selectMultipleImages: 'Mund të zgjidhni shumë imazhe njëkohësisht',
    selectedImages: 'Imazhet e Zgjedhura',
    submitListing: 'Dërgo Postimin',
    mustBeLoggedIn: 'Duhet të jeni të kyçur për të shtuar një postim.',
    listingAddedSuccessfully: '✅ Postimi u shtua me sukses!',
    failedToAddListing: '❌ Dështoi shtimi i postimit.',
    errorOccurred: '⚠️ Ndodhi një gabim gjatë ngarkimit të postimit.',
    uploadingListing: 'Duke Ngarkuar Postimin...',
    preparingListing: 'Duke përgatitur postimin tuaj...',
    uploadingImages: 'Duke ngarkuar imazhet...',
    listingCreatedSuccess: 'Postimi u krijua me sukses!',
    success: 'Sukses',
    redirectingToListing: 'Duke ju ridrejtuar te postimi juaj...',
    updatingForm: 'Duke përditësuar formularin',
    businessPropertyNote: 'Pronë Biznesi',
    businessPropertyDescription: 'Përshkruani detajet e biznesit në përshkrimin (lloji i biznesit, pajisjet, etj.)',
    landPropertyNote: 'Pronë Toke',
    landPropertyDescription: 'Specifikoni madhësinë e tokës dhe destinimin e saj në përshkrim.',

    // Profile updates
    updatingProfile: 'Duke përditësuar profilin...',
    updatingListing: 'Duke përditësuar postimin...',
    profileUpdatedSuccess: 'Profili u përditësua me sukses!',
    listingUpdatedSuccess: 'Postimi u përditësua me sukses!',
    listingUpdateError: 'Dështoi përditësimi i postimit. Ju lutemi provoni përsëri.',
    listingDeletedSuccess: 'Postimi u fshi me sukses!',
    listingDeleteError: 'Dështoi fshirja e postimit. Ju lutemi provoni përsëri.',
    listingBoostedSuccess: 'Postimi u promovua me sukses! Do të promovohet për 14 ditë.',
    listingBoostError: 'Dështoi promovimi i postimit. Ju lutemi provoni përsëri.',
    emailVerificationSent: 'U dërgua një lidhje verifikimi në email-in tuaj të ri. Ju lutemi verifikoni adresën e re të email-it për të përfunduar ndryshimin.',
    emailAlreadyInUse: 'Ky email është tashmë në përdorim nga një llogari tjetër',
    invalidEmail: 'Adresë email-i e pavlefshme',

    // Auth Handler
    invalidLink: 'Lidhje e pavlefshme ose e skaduar',
    enterNewPassword: 'Ju lutemi vendosni fjalëkalimin tuaj të ri',
    emailVerifiedSuccess: 'Email-i juaj u verifikua me sukses! Tani mund të hyni.',
    emailRecoveredSuccess: 'Email-i juaj u rikuperua me sukses!',
    unsupportedAction: 'Veprim i pambështetur',
    linkExpired: 'Kjo lidhje ka skaduar. Ju lutemi kërkoni një të re.',
    linkInvalid: 'Kjo lidhje është e pavlefshme ose është përdorur tashmë.',
    actionFailed: 'Veprimi dështoi. Ju lutemi provoni përsëri.',
    passwordResetSuccess: 'Fjalëkalimi juaj u rivendos me sukses! Duke ju ridrejtuar në hyrje...',
    passwordResetFailed: 'Dështoi rivendosja e fjalëkalimit. Ju lutemi provoni përsëri.',
    redirectingToLogin: 'Duke ju ridrejtuar në hyrje...',
    goToLogin: 'Shko në Hyrje',
    requestNewLink: 'Kërko Lidhje të Re',
    newPassword: 'Fjalëkalim i Ri',
    confirmNewPassword: 'Konfirmo Fjalëkalimin e Ri',

    success: 'Sukses!',
    error: 'Gabim!',
    warning: 'Paralajmërim!',
    okay: 'Në rregull',
    confirmDelete: 'Konfirmo Fshirjen',
    deleteListingConfirm: 'Jeni i sigurt që doni të fshini këtë postim? Ky veprim nuk mund të zhbëhet.',
    deleteNow: 'Fshi Tani',
    profileUpdateError: 'Dështoi përditësimi i profilit',
    accountDeletionCancelled: 'Fshirja e llogarisë u anulua.',
    confirmPasswordToDelete: 'Ju lutemi konfirmoni fjalëkalimin tuaj për të fshirë llogarinë:',
    wrongPassword: 'Fjalëkalim i pasaktë.',
    accountDeletedSuccess: 'Llogaria juaj është fshirë përgjithmonë.',
    accountDeletionError: 'Dështoi fshirja e llogarisë',
    confirmAccountDeletion: 'Jeni absolutisht të sigurt që doni të fshini llogarinë tuaj?',
    deletingAccount: 'Duke fshirë...',
    invalidPhoneNumber: 'Ju lutemi vendosni një numër telefoni të vlefshëm me kodin e shtetit',

    // Boost modal
    promoteYourListing: '🚀 Promovo Postimin Tënd',
    maxVisibilityDesc: 'Merr dukshmëri maksimale dhe tërheq më shumë blerës - plotësisht FALAS!',
    featuredListingPlan: '⭐ Postim i Promovuar',
    promotePropertyDesc: 'Promovo postimin tënd për 14 ditë pa kosto',
    free: 'FALAS',
    days14: '14 ditë',
    featuredHomepage: 'E promovuar në kryefaqe për dukshmëri maksimale',
    topSearchResults: 'Në krye të rezultateve të kërkimit në të gjitha kategoritë',
    specialBadge: 'Shenjë speciale e promovimit në postimin tënd',
    premiumPlacement: '14 ditë vendosje premium',
    increasedViews: 'Rritje e shikimeve dhe angazhimit',
    promoteButton: '🚀 Promovo FALAS (14 Ditë)',
    promotingListing: 'Duke promovuar postimin...',
    completelyFree: 'Plotësisht Falas:',
    completelyFreeDesc: 'Nuk kërkohet pagesë! Postimi yt do të promovohet automatikisht për 14 ditë dhe do të shfaqet në krye të rezultateve të kërkimit.',

    // Paid Promotion (€1)
    boostPropertyFor15Days: 'Promovo pronën tënde për 15 ditë',
    days15: '15 ditë',
    days15Premium: '15 ditë vendosje premium',
    payWithCreditCard: 'Paguaj me Kartë Krediti/Debiti - €1',
    payWithCardShort: 'Paguaj me Kartë Krediti ose Debiti',
    securePayment: 'Pagesë e Sigurt',
    securePaymentDesc: 'Paguani direkt me kartën tuaj të kreditit ose debitit. Postimi juaj do të promovohet menjëherë pas konfirmimit të pagesës.',
    securePaymentPoweredBy: 'Pagesë e sigurt e mundësuar nga PayPal',
    boostListingButton: 'Promovo Pronën',

    // Filters
    allTypes: 'Të gjitha',
    sale: 'Shitje',
    rent: 'Qera',
    privateHome: 'Shtëpi Private',
    apartment: 'Apartament',
    land: 'Tokë',
    minPrice: 'Çmimi minimal',
    maxPrice: 'Çmimi maksimal',
    filters: 'Filtrat',

    // Common
    loading: 'Duke ngarkuar...',
    error: 'Gabim',
    success: 'Sukses',
    submit: 'Dërgo',
    back: 'Kthehu',
    next: 'Përpara',
    previous: 'Mbrapa',
    close: 'Mbyll',
    save: 'Ruaj',
    delete: 'Fshi',
    confirm: 'Konfirmo',
    yes: 'Po',
    no: 'Jo',

    // Footer
    footerTagline: 'Platforma juaj e besueshme për blerjen, shitjen dhe qeranë e pronave premium në mbarë Shqipërinë.',
    quickLinks: 'Lidhje të Shpejta',
    buyProperty: 'Bli Pronë',
    rentProperty: 'Pronë me Qera',
    listYourProperty: 'Listo Pronën Tënde',
    allProperties: 'Të gjitha Pronat',
    resources: 'Burimet',
    about: 'Rreth nesh',
    howItWorks: 'Si Funksionon',
    privacyPolicy: 'Politika e Privatësisë',
    termsOfService: 'Kushtet e Shërbimit',
    contactUs: 'Na Kontaktoni',
    followUs: 'Na ndiqni',
    allRightsReserved: 'Të gjitha të drejtat e rezervuara.',
    cookiePolicy: 'Politika e Cookies',
    termsOfUse: 'Kushtet e Përdorimit',

    // About page
    aboutHeroTitle: 'Rreth Nesh',
    aboutHeroSubtitle: 'Partneri juaj i besueshëm për zgjidhje të pasurive të paluajtshme në Shqipëri',
    aboutStatsProperties: 'Prona',
    aboutStatsClients: 'Klientë të Kënaqur',
    aboutStatsAgents: 'Agjentë Profesionistë',
    aboutStatsYears: 'Vite Eksperiencë',
    aboutStoryTitle: 'Historia Jonë',
    aboutStoryPara1: 'RealEstateAL u themelua me një vizion të thjeshtë: të bëjmë blerjen, shitjen dhe qeramarrjen e pronave në Shqipëri më të lehtë, më transparente dhe më të aksesueshme për të gjithë.',
    aboutStoryPara2: 'Që nga fillimi ynë, jemi angazhuar për të ofruar shërbimin më të mirë të mundshëm për klientët tanë. Platforma jonë lidh blerësit, shitësit dhe qeramarrësit me prona cilësore në të gjithë Shqipërinë.',
    aboutStoryPara3: 'Sot, ne jemi krenarë që jemi njëra nga platformat kryesore të pasurive të paluajtshme në Shqipëri, duke ndihmuar qindra familje dhe biznese të gjejnë pronën e tyre të përsosur çdo vit.',
    aboutValuesTitle: 'Vlerat Tona',
    aboutValuesSubtitle: 'Parimet që na udhëheqin në çdo gjë që bëjmë',
    aboutValueTrust: 'Besueshmëri',
    aboutValueTrustDesc: 'Ne ndërtojmë besimin përmes transparencës, ndershmërisë dhe integritetit në çdo transaksion. Të gjitha pronat janë verifikuar dhe të garantuara.',
    aboutValueInnovation: 'Inovacion',
    aboutValueInnovationDesc: 'Ne përdorim teknologjinë më të fundit, duke përfshirë AI-në e Google Gemini, për të ofruar përvojën më të mirë të mundshme për përdoruesit tanë.',
    aboutValueExcellence: 'Përsosmëri',
    aboutValueExcellenceDesc: 'Ne përpiqemi për përsosmëri në çdo aspekt të shërbimit tonë, nga cilësia e pronave deri tek mbështetja e klientit.',
    aboutTeamTitle: 'Takoni Ekipin Tonë',
    aboutTeamSubtitle: 'Profesionistët e dedikuar pas suksesit tuaj',
    aboutTeamCEO: 'Drejtues Ekzekutiv',
    aboutTeamCEORole: 'CEO & Themelues',
    aboutTeamCTO: 'Drejtor Teknologjie',
    aboutTeamCTORole: 'CTO',
    aboutTeamHead: 'Drejtor Shitjesh',
    aboutTeamHeadRole: 'Drejtues i Shitjeve',
    aboutCTATitle: 'Gati për të Gjetur Shtëpinë e Ëndrrave Tuaja?',
    aboutCTASubtitle: 'Filloni udhëtimin tuaj sot me RealEstateAL',
    aboutCTABrowse: 'Shfleto Pronat',
    aboutCTAContact: 'Na Kontaktoni',

    // Messages
    loginRequired: 'Ju lutemi kyçuni për të shtuar listë.',
    loginToBuy: 'Ju lutemi kyçuni për të kontaktuar pronarin.',
    addedToFavorites: 'U shtua në të preferuarat',
    removedFromFavorites: 'U hoq nga të preferuarat',
    listingDeleted: 'Lista u fshi me sukses',
    listingUpdated: 'Lista u përditësua me sukses',
    boostSuccess: 'Lista u promovua me sukses! Do të promvohet për 14 ditë.',
    boostError: 'Dështoi promovimi i listës',

    // Favorites page
    myFavorites: 'Të Preferuarat e Mia',
    savedProperties: 'Prona të ruajtura',
    property: 'Pronë',
    properties: 'Prona',
    loadingFavorites: 'Duke ngarkuar të preferuarat tuaja...',
    noFavoritesYet: 'Ende nuk ka të preferuara',
    startSavingProperties: 'Filloni të ruani pronat që ju pëlqejnë duke klikuar ikonën e zemrës',
    browseProperties: 'Shfletoni Pronat',

    // Privacy Policy
    privacyPolicyTitle: 'Politika e Privatësisë',
    lastUpdated: 'Përditësuar Më',
    privacyLastUpdated: '3 Nëntor 2025',
    privacyIntroTitle: 'Hyrje',
    privacyIntroText1: 'RealEstateAL ("ne", "na", ose "ynë") respekton privatësinë tuaj dhe është i përkushtuar të mbrojë informacionin personal që ju ndani me ne. Kjo Politikë e Privatësisë shpjegon se si grumbullojmë, përdorim, ruajmë dhe mbrojmë informacionin tuaj kur përdorni platformën tonë.',
    privacyIntroText2: 'Duke përdorur shërbimin tonë, ju pranoni praktikat e përshkruara në këtë politikë.',
    privacyInfoCollectTitle: 'Informacioni që Grumbullojmë',
    privacyPersonalInfo: 'Informacion Personal',
    privacyInfoName: 'Emri dhe mbiemri',
    privacyInfoEmail: 'Adresa e email-it',
    privacyInfoPhone: 'Numri i telefonit',
    privacyInfoAddress: 'Adresa',
    privacyPropertyInfo: 'Informacioni i Pronës',
    privacyInfoPropertyDetails: 'Detajet e pronës (lloji, madhësia, çmimi)',
    privacyInfoPhotos: 'Fotografi dhe përshkrime',
    privacyInfoLocation: 'Vendndodhja',
    privacyInfoPrice: 'Informacioni i çmimit',
    privacyUsageData: 'Të Dhënat e Përdorimit',
    privacyInfoBrowser: 'Lloji i shfletuesit dhe versioni',
    privacyInfoIP: 'Adresa IP',
    privacyInfoPages: 'Faqet e vizituara',
    privacyInfoSearches: 'Kërkimet dhe filtrat e përdorura',
    privacyHowWeUseTitle: 'Si e Përdorim Informacionin Tuaj',
    privacyUseProvideServices: 'Për të ofruar dhe mirëmbajtur shërbimin tonë',
    privacyUseConnect: 'Për të lidhur blerësit dhe shitësit',
    privacyUseImprove: 'Për të përmirësuar platformën tonë',
    privacyUseSendUpdates: 'Për t\'ju dërguar përditësime dhe njoftimet e kërkuara',
    privacyUseComply: 'Për të përmbushur detyrimet ligjore',
    privacySharingTitle: 'Ndarja e Informacionit',
    privacySharingText: 'Ne mund të ndajmë informacionin tuaj me:',
    privacyShareBuyers: 'Blerësit dhe qeramarrësit e interesuar për prona të listuara',
    privacyShareProviders: 'Ofruesit e shërbimit që na ndihmojnë të operojmë platformën',
    privacySharePayment: 'Procesorët e pagesave (PayPal) për transaksionet e boost-it të pronave',
    privacyShareLegal: 'Autoritetet ligjore kur kërkohet nga ligji',
    privacyShareConsent: 'Palët e treta me pëlqimin tuaj',

    // Third-Party Services
    privacyThirdPartyTitle: 'Shërbimet e Palëve të Treta',
    privacyThirdPartyText: 'Ne përdorim gjithashtu shërbime të besueshme të palëve të treta për të operuar dhe përmirësuar platformën tonë, duke përfshirë Google Analytics (për statistikat e përdorimit), Firebase (për autentikimin dhe ruajtjen e të dhënave), Cloudinary (për hosting-un e imazheve), Google reCAPTCHA (për mbrojtjen nga spam-i), Google Gemini AI (për asistencën inteligjente) dhe Mapbox (për hartat interaktive). Këto shërbime mund të mbledhin të dhëna të kufizuara sipas politikave të tyre të privatësisë.',
    privacyThirdPartyAnalytics: 'për statistikat e përdorimit dhe analizën e trafikut të faqes',
    privacyThirdPartyFirebase: 'për autentikimin e sigurt të përdoruesve dhe ruajtjen e të dhënave',
    privacyThirdPartyCloudinary: 'për hosting-un dhe optimizimin e imazheve të pronave',
    privacyThirdPartyRecaptcha: 'për mbrojtjen kundër spam-it dhe botëve automatikë',
    privacyThirdPartyGemini: 'për asistencën e inteligjencës artificiale dhe chatbot-in',
    privacyThirdPartyMapbox: 'për hartat interaktive dhe vizualizimin e vendndodhjes së pronave',
    privacyThirdPartyNote: 'Këto shërbime veprojnë sipas politikave të tyre të privatësisë dhe mund të mbledhin informacione sipas kushteve të tyre.',

    // Payment Processing
    privacyPaymentTitle: 'Përpunimi i Pagesave',
    privacyPaymentText: 'Për shërbimet me pagesë si Featured Listing (Boost), ne përdorim PayPal për të përpunuar pagesa në mënyrë të sigurt.',
    privacyPaymentBoostTitle: 'Boost Listing (Listim i Promovuar)',
    privacyPaymentBoostText: 'Kur përdoruesit paguajnë për të promovuar listimin e tyre, transaksioni përpunohet përmes PayPal. Ne nuk ruajmë detajet e kartës së kreditit tuaj.',
    privacyPaymentInfo1: 'Informacioni i pagesës përpunohet në mënyrë të sigurt nga PayPal',
    privacyPaymentInfo2: 'Ne ruajmë vetëm ID-në e transaksionit, shumën dhe statusin për qëllime të evidencës',
    privacyPaymentInfo3: 'PayPal mund të mbledhë informacione shtesë sipas Politikës së tyre të Privatësisë',
    privacyPaymentInfo4: 'Historiku i pagesave tuaja është i disponueshëm në profilin tuaj',
    privacyPaymentNote: 'Shënim: Ne nuk kemi akses në detajet e plota të kartës suaj. Të gjitha të dhënat e pagesave trajtohen nga PayPal në përputhje me standardet e industrisë (PCI DSS).',

    privacySecurityTitle: 'Siguria e të Dhënave',
    privacySecurityText: 'Ne zbatojmë masa të arsyeshme teknike dhe organizative për të mbrojtur informacionin tuaj personal nga humbja, keqpërdorimi, qasja e paautorizuar, zbulimi, ndryshimi ose shkatërrimi.',
    privacyCookiesTitle: 'Cookies',
    privacyCookiesText: 'Ne përdorim cookies për të përmirësuar përvojën tuaj. Cookies janë skedarë të vegjël që ruhen në pajisjen tuaj. Ju mund t\'i menaxhoni preferencat e cookies përmes cilësimeve të shfletuesit tuaj.',
    privacyCookieSession: 'Session cookies - për funksionalitetin bazë',
    privacyCookiePreferences: 'Preference cookies - për të mbajtur preferencat tuaja',
    privacyCookieAnalytics: 'Analytics cookies - për të kuptuar si përdorni platformën',

    // Data Retention
    privacyRetentionTitle: 'Ruajtja e të Dhënave',
    privacyRetentionText: 'Ne ruajmë të dhënat personale për aq kohë sa është e nevojshme për të ofruar shërbime, për t\'iu përgjigjur detyrimeve ligjore, për të zgjidhur mosmarrëveshjet dhe për të zbatuar marrëveshjet tona.',
    privacyRetentionActive: 'Listimet e pronave mbeten aktive derisa të fshihen nga përdoruesi',
    privacyRetentionInactive: 'Llogaritë joaktive mund të fshihen pas 3 vitesh',
    privacyRetentionLegal: 'Të dhënat e transaksioneve ruhen për 7 vjet për qëllime ligjore',

    // Legal Basis
    privacyLegalBasisTitle: 'Baza Ligjore për Përpunimin',
    privacyLegalBasisText: 'Ne përpunojmë të dhënat tuaja personale bazuar në bazat e mëposhtme ligjore:',
    privacyLegalBasisConsent: 'Pëlqimi - për email-et marketingu dhe komunikime promocionale',
    privacyLegalBasisContract: 'Ekzekutimi i kontratës - për transaksionet e pronave dhe ofrimin e shërbimeve',
    privacyLegalBasisLegitimate: 'Interesi legjitim - për përmirësimin e shërbimit dhe parandalimin e mashtrimit',
    privacyLegalBasisLegal: 'Detyrimi ligjor - për mbajtjen e të dhënave dhe raportimin',

    // Data Transfers
    privacyDataTransferTitle: 'Transferimet Ndërkombëtare të të Dhënave',
    privacyDataTransferText: 'Të dhënat tuaja mund të transferohen dhe ruhen në serverë të vendosur jashtë Shqipërisë, duke përfshirë brenda Bashkimit Evropian dhe Shtetet e Bashkuara. Ne sigurojmë që mbrojtje të përshtatshme janë në vend për të mbrojtur të dhënat tuaja në përputhje me këtë Politikë të Privatësisë.',

    // Enhanced Rights
    privacyRightsIntro: 'Sipas GDPR dhe ligjeve për mbrojtjen e të dhënave, ju keni të drejtat e mëposhtme:',
    privacyRightsTitle: 'Të Drejtat Tuaja',
    privacyRightAccess: 'Të qaseni informacionin tuaj personal',
    privacyRightCorrect: 'Të korrigjoni informacion jo të saktë',
    privacyRightDelete: 'Të kërkoni fshirjen e informacionit tuaj',
    privacyRightObject: 'Të kundërshtoni përpunimin e informacionit tuaj',
    privacyRightExport: 'Të eksportoni të dhënat tuaja në një format të lexueshëm nga makina',
    privacyRightWithdraw: 'Të tërhiqni pëlqimin në çdo kohë pa ndikuar ligjshmërinë e përpunimit të bazuar në pëlqim para tërheqjes',

    privacyOwnershipTitle: 'Pronësia dhe Mbrojtja e Faqes',
    privacyOwnershipText1: 'Kjo faqe interneti, përfshirë të gjithë përmbajtjen, dizajnin, kodin dhe veçoritë e saj, është pronë ekskluzive e RealEstateAL dhe mbrojtur nga ligjet e pronësisë intelektuale. Çdo përdorim, riprodhim ose shpërndarje e paautorizuar është rreptësisht e ndaluar.',
    privacyOwnershipText2: 'Duke përdorur këtë platformë, ju pranoni se përdorimi i saj është "siç është" dhe "sipas disponueshmërisë". Ne nuk garantojmë që shërbimi do të jetë i pandërprerë ose pa gabime. Mund të ndodhin gabime teknike dhe ne jemi duke punuar vazhdimisht për të përmirësuar platformën tonë.',
    privacyOwnershipText3: 'Përpjekjet për shkelje të sigurisë, hacking, ose çdo veprim i paautorizuar kundër platformës tonë do të hetohen dhe do të ndjeken ligjërisht në masën më të plotë të ligjit.',

    privacyChildrenTitle: 'Privatësia e Fëmijëve',
    privacyChildrenText: 'Shërbimi ynë nuk është i destinuar për persona nën 18 vjeç. Ne nuk grumbullojmë me vetëdije informacion personal nga fëmijët.',
    privacyChangesTitle: 'Ndryshimet në këtë Politikë',
    privacyChangesText: 'Ne mund të përditësojmë këtë Politikë të Privatësisë periodikisht. Ju njoftojmë për çdo ndryshim duke postuar politikën e re në këtë faqe dhe duke përditësuar datën "Përditësuar Më".',
    privacyContactTitle: 'Na Kontaktoni',
    privacyContactText: 'Nëse keni pyetje rreth kësaj Politike të Privatësisë, na kontaktoni në:',

    // Terms of Service
    termsTitle: 'Kushtet e Shërbimit',
    termsLastUpdated: '3 Nëntor 2025',
    termsIntroTitle: 'Hyrje',
    termsIntroText1: 'Mirë se vini në RealEstateAL! Këto Kushte të Shërbimit ("Kushtet") rregullojnë përdorimin tuaj të platformës sonë.',
    termsIntroText2: 'Ju lutemi lexoni këto Kushte me kujdes përpara se të përdorni shërbimin tonë.',
    termsAcceptanceTitle: 'Pranimi i Kushteve',
    termsAcceptanceText: 'Duke qasur ose përdorur RealEstateAL, ju pranoni të jeni të detyruar nga këto Kushte. Nëse nuk jeni dakord me ndonjë pjesë të këtyre Kushteve, ju nuk mund të përdorni shërbimin tonë.',
    termsAccountTitle: 'Regjistrimi i Llogarisë',
    termsAccountText: 'Për të përdorur disa veçori të platformës sonë, duhet të krijoni një llogari. Ju pranoni që:',
    termsAccountAccurate: 'Të ofroni informacion të saktë dhe të plotë',
    termsAccountSecurity: 'Të mbani kredencialet tuaja të kyçjes të sigurta',
    termsAccountResponsible: 'Jeni përgjegjës për të gjitha aktivitetet nën llogarinë tuaj',
    termsAccountNotify: 'Të na njoftoni menjëherë për çdo përdorim të paautorizuar',
    termsListingsTitle: 'Listimet e Pronave',
    termsListingsText: 'Kur postoni një pronë në platformën tonë, ju garantoni që:',
    termsListingsOwnership: 'Keni të drejtë ligjore për të listuar pronën',
    termsListingsAccurate: 'Të gjitha informacionet janë të sakta dhe të vërteta',
    termsListingsLegal: 'Pronai përmbush të gjitha kërkesat ligjore',
    termsListingsPhotos: 'Keni të drejtën të përdorni të gjitha fotografitë e dhëna',
    termsListingsProhibited: 'Lista nuk përmban material të ndaluar ose mashtruese',
    termsConductTitle: 'Sjellja e Përdoruesit',
    termsConductText: 'Ju pajtoheni të mos:',
    termsConductIllegal: 'Përdorni platformën për qëllime të paligjshme',
    termsConductHarmful: 'Postoni përmbajtje të dëmshme, ofenduese ose të papërshtatshme',
    termsConductFraud: 'Angazhoheni në aktivitete mashtruese',
    termsConductSpam: 'Dërgoni spam ose mesazhe të pakërkuara',
    termsConductInterfere: 'Ndërhyni me funksionimin e platformës',
    termsConductInfringe: 'Shkelni të drejtat e pronësisë intelektuale të të tjerëve',
    termsFeesTitle: 'Tarifat dhe Pagesat',
    termsFeesText: 'RealEstateAL ofron:',
    termsFeesBasic: 'Listimi bazik falas i pronave',
    termsFeesFeatured: 'Listime të promovuara me pagesë (14 ditë promovim për tarifë)',
    termsFeesNonRefundable: 'Të gjitha tarifat janë të pakthyeshme',
    termsIPTitle: 'Pronësia Intelektuale',
    termsIPText1: 'Platforma, përmbajtja dhe materialet e saj janë pronë e RealEstateAL ose licencuesve tanë. Ju nuk mund të kopjoni, modifikoni, shpërndani ose përdorni materialin tonë pa leje.',
    termsIPText2: 'Duke ngarkuar përmbajtje, ju na jepni një licencë jo-ekskluzive, të transferueshme, botërore për të përdorur, shfaqur dhe promovuar përmbajtjen tuaj në platformën tonë.',
    termsDisclaimerTitle: 'Mohimi i Garancive',
    termsDisclaimerText1: 'PLATFORMA OFROHET "SIKUNDËR ËSHTË" DHE "SIÇ ËSHTË E DISPONUESHME". NE NUK JAPIM GARANCI TË LLOJIT, TË QARTA OSE TË NËNKUPTUARA.',
    termsDisclaimerText2: 'Ne nuk garantojmë që shërbimi do të jetë i pandërprerë, i sigurt ose pa gabime. Ju përdorni platformën me rrezikun tuaj.',
    termsLiabilityTitle: 'Kufizimi i Përgjegjësisë',
    termsLiabilityText: 'NË ASNJË RAST REALESTATEAL NUK DO TË JETË PËRGJEGJËSE PËR ASNJË DËMTIM TË DREJTPËRDREJTË, TË TËRTHORTË, AKSIDENTAL, VEÇANTË OSE PASUES QË RRJEDHIN NGA PËRDORIMI OSE PAAFTËSIA E PËRDORIMIT TË PLATFORMËS.',
    termsIndemnityTitle: 'Dëmshpërblimi',
    termsIndemnityText: 'Ju pajtoheni të mbrojeni, dëmshpërbleni dhe mbani të padëmshëm RealEstateAL nga çdo pretendim, dëm, humbje ose shpenzim që rrjedh nga shkelja juaj e këtyre Kushteve.',
    termsTerminationTitle: 'Ndërprerja',
    termsTerminationText: 'Ne rezervojmë të drejtën të pezullojmë ose ndërpresim llogarinë tuaj dhe qasjen në platformë në çdo kohë, pa njoftim paraprak, për sjellje që shkelen këto Kushte.',
    termsGoverningLawTitle: 'Ligji Drejtues',
    termsGoverningLawText: 'Këto Kushte rregullohen nga ligjet e Republikës së Shqipërisë. Çdo mosmarrëveshje do të zgjidhet në gjykatat e Tiranës.',
    termsChangesTitle: 'Ndryshimet në Kushte',
    termsChangesText: 'Ne mund të përditësojmë këto Kushte periodikisht. Përdorimi i vazhdueshëm i platformës pas ndryshimeve përbën pranimin tuaj të kushteve të reja.',
    termsOwnershipTitle: 'Pronësia dhe Mbrojtja e Faqes',
    termsOwnershipText1: 'Kjo faqe interneti, përfshirë të gjithë përmbajtjen, dizajnin, kodin dhe veçoritë e saj, është pronë ekskluzive e RealEstateAL dhe mbrojtur nga ligjet e pronësisë intelektuale. Çdo përdorim, riprodhim ose shpërndarje e paautorizuar është rreptësisht e ndaluar.',
    termsOwnershipText2: 'Duke përdorur këtë platformë, ju pranoni se përdorimi i saj është "siç është" dhe "sipas disponueshmërisë". Ne nuk garantojmë që shërbimi do të jetë i pandërprerë ose pa gabime. Mund të ndodhin gabime teknike dhe ne jemi duke punuar vazhdimisht për të përmirësuar platformën tonë.',
    termsOwnershipText3: 'Përpjekjet për shkelje të sigurisë, hacking, ose çdo veprim i paautorizuar kundër platformës tonë do të hetohen dhe do të ndjeken ligjërisht në masën më të plotë të ligjit.',
    termsContactTitle: 'Na Kontaktoni',
    termsContactText: 'Nëse keni pyetje rreth këtyre Kushteve, na kontaktoni në:',

    // Legal page (combined Privacy + Terms)
    legalTitle: 'Ligjore & Privatësia',
    legalSubtitle: 'Politika e Privatësisë dhe Kushtet e Shërbimit',

    // Login page
    login: 'Kyçu',
    createAccount: 'Krijoni Llogari',
    firstName: 'Emri',
    lastName: 'Mbiemri',
    phoneNumber: 'Numri i Telefonit',
    person: 'Person',
    agent: 'Agent',
    agency: 'Agjensi',
    email: 'Email',
    password: 'Fjalëkalimi',
    confirmPassword: 'Konfirmo Fjalëkalimin',
    processing: 'Duke procesuar...',
    signUp: 'Regjistrohu',
    forgotPassword: 'Harruat fjalëkalimin?',
    alreadyHaveAccount: 'Keni tashmë një llogari?',
    dontHaveAccount: 'Nuk keni llogari?',
    agreeToTermsPart1: 'Duke u regjistruar, ju pranoni',
    and: 'dhe',
    mustAgreeToTerms: 'Ju duhet të pranoni Kushtet e Shërbimit dhe Politikën e Privatësisë për të vazhduar.',
    resetPassword: 'Rivendos Fjalëkalimin',
    enterEmailReset: 'Shkruani adresën tuaj të email-it dhe ne do t\'ju dërgojmë një lidhje për të rivendosur fjalëkalimin tuaj.',
    emailAddress: 'Adresa e Email-it',
    sendResetLink: 'Dërgo Lidhjen e Rivendosjes',
    sending: 'Duke dërguar...',

    // Cookie Consent
    cookieConsentTitle: 'Njoftim për Cookies',
    cookieConsentText: 'Ne përdorim cookies për të përmirësuar përvojën tuaj. Duke vazhduar të përdorni këtë faqe, ju pranoni përdorimin e cookies sipas',
    cookieSettings: 'Cilësimet',
    cookieNecessaryOnly: 'Vetëm të Nevojshme',
    cookieAcceptAll: 'Prano të Gjitha',
    acceptAll: 'Prano të Gjitha',
    rejectAll: 'Refuzo të Gjitha',
    cookieSettingsTitle: 'Cilësimet e Cookies',
    cookieSettingsDescription: 'Zgjidhni cilat lloje të cookies dëshironi të aktivizoni. Ju mund të ndryshoni këto cilësime në çdo kohë.',
    cookieNecessaryTitle: 'Cookies të Nevojshme',
    necessaryCookies: 'Cookies të Nevojshme',
    necessaryCookiesDesc: 'Këto cookies janë thelbësore për funksionimin e faqes dhe nuk mund të çaktivizohen.',
    analyticsCookies: 'Cookies Analitike',
    analyticsCookiesDesc: 'Këto cookies na ndihmojnë të kuptojmë se si vizitorët ndërveprojnë me faqen tonë.',
    marketingCookies: 'Cookies Marketingu',
    marketingCookiesDesc: 'Këto cookies përdoren për të shfaqur reklama që janë më të rëndësishme për ju.',
    cookieAlwaysActive: 'Gjithmonë Aktive',
    cookieNecessaryDescription: 'Këto cookies janë thelbësore për funksionimin e faqes dhe nuk mund të çaktivizohen. Përfshijnë kyçjen dhe ruajtjen e preferencave tuaja.',
    cookieAnalyticsTitle: 'Cookies Analitike',
    cookieAnalyticsDescription: 'Këto cookies na ndihmojnë të kuptojmë se si vizitorët ndërveprojnë me faqen tonë duke mbledhur dhe raportuar informacion në mënyrë anonime.',
    cookieMarketingTitle: 'Cookies Marketingu',
    cookieMarketingDescription: 'Këto cookies përdoren për të shfaqur reklama që janë më të rëndësishme për ju dhe interesat tuaja. Ato gjithashtu përdoren për të kufizuar numrin e herëve që shikoni një reklamë.',
    cookieSavePreferences: 'Ruaj Preferencat',
    cookiePreferences: 'Preferencat e Cookies',
    savePreferences: 'Ruaj Preferencat',
    back: 'Kthehu',

    // Consent Management
    consentManagement: 'Menaxhimi i Pëlqimit',
    consentManagementDesc: 'Menaxhoni preferencat tuaja të privatësisë dhe shikoni historikun e pëlqimit.',
    currentStatus: 'Statusi Aktual',
    lastUpdated: 'Përditësuar Së Fundi',
    version: 'Versioni',
    status: 'Statusi',
    consented: 'U Pranua',
    withdrawn: 'U Tërhoq',
    accepted: 'U Pranua',
    rejected: 'U Refuzua',
    preferencesSaved: 'Preferencat u ruajtën me sukses!',
    errorSavingPreferences: 'Gabim gjatë ruajtjes së preferencave.',
    confirmWithdrawConsent: 'Jeni i sigurt që dëshironi të tërhiqni pëlqimin tuaj?',
    consentWithdrawn: 'Pëlqimi u tërhoq me sukses.',
    withdrawConsent: 'Tërhiq Pëlqimin',
    viewHistory: 'Shiko Historikun',
    consentHistory: 'Historiku i Pëlqimit',
    saving: 'Duke Ruajtur...',

    creatingAccount: 'Duke krijuar llogarinë tuaj...',
    loggingIn: 'Duke ju kyçur...',
    welcome: 'Mirë se vini!',
    hello: 'Përshëndetje, {name}!',
    redirectingHome: 'Duke ridrejtuar në faqen kryesore...',
    passwordsDoNotMatch: 'Fjalëkalimet nuk përputhen!',
    verificationEmailSent: 'Email-i i verifikimit u dërgua! Ju lutemi kontrolloni kutinë tuaj dhe verifikoni email-in tuaj.',
    pleaseVerifyEmail: 'Ju lutemi verifikoni email-in tuaj para se të kyçeni. Kontrolloni kutinë tuaj për lidhjen e verifikimit.',
    verifyYourEmail: 'Verifikoni Email-in Tuaj',
    almostThere: 'Pothuajse gati! Vetëm një hap i fundit.',
    verificationEmailSentTo: 'Kemi dërguar një email verifikimi në:',
    checkInboxAndClickLink: 'Ju lutemi kontrolloni kutinë tuaj dhe klikoni lidhjen e verifikimit.',
    nextSteps: 'Hapat e Radhës',
    openEmailInbox: 'Hapni kutinë tuaj të email-it',
    clickVerificationLink: 'Klikoni lidhjen e verifikimit në email',
    returnAndClickConfirm: 'Kthehuni këtu dhe klikoni "Kam Verifikuar"',
    iHaveVerified: 'Kam Verifikuar Email-in',
    checking: 'Duke kontrolluar...',
    resendEmail: 'Ridërgo Email-in',
    cancelAndGoBack: 'Anulo dhe Kthehu',
    didntReceiveEmail: 'Nuk e morët email-in?',
    checkSpamFolder: 'Kontrolloni dosjen e spam-it.',
    emailNotVerifiedYet: 'Email-i juaj nuk është verifikuar ende. Ju lutemi kontrolloni kutinë tuaj dhe klikoni lidhjen e verifikimit.',
    failedToResendEmail: 'Dështoi dërgimi i email-it. Ju lutemi provoni përsëri.',
    pleaseLoginAgain: 'Ju lutemi kyçuni përsëri për të kontrolluar statusin e verifikimit.',
    resetEmailSent: 'Email-i i rivendosjes u dërgua! Kontrolloni kutinë tuaj.',
    resetEmailError: 'Email-i nuk u gjet. Ju lutemi kontrolloni dhe provoni përsëri.',
    emailNotFound: 'Email-i nuk u gjet në sistemin tonë.',
    invalidEmail: 'Adresa e email-it nuk është e vlefshme.',
    recaptchaNotReady: 'Verifikimi i sigurisë po ngarkohet. Ju lutemi provoni përsëri.',
    recaptchaProtected: 'Kjo faqe është e mbrojtur nga reCAPTCHA dhe aplikohen Politika e Privatësisë dhe Kushtet e Shërbimit të Google.',
    tooManyAttempts: 'Shumë përpjekje të dështuara. Ju lutemi prisni {seconds} sekonda para se të provoni përsëri.',
    loginError: 'Email ose fjalëkalim i gabuar. {attempts} përpjekje të mbetura.',
    accountLocked: '🔒 Llogaria e Kyçur Përkohësisht',
    waitBeforeRetry: 'Prisni {seconds} sekonda para se të provoni përsëri.',
    locked: 'E Kyçur',
    emailAlreadyInUse: 'Ky email është tashmë në përdorim. Ju lutemi kyçuni ose përdorni një email tjetër.',
    weakPassword: 'Fjalëkalimi është shumë i dobët. Ju lutemi përdorni të paktën 6 karaktere.',
    pleaseWait: 'Ju lutemi prisni...',
    joinOurCommunity: 'Bashkohuni me komunitetin tonë sot',
    welcomeBack: 'Mirë se u kthyet! Hyni në llogarinë tuaj',
  },

  en: {
    // Navigation
    home: 'Home',
    listings: 'Listings',
    buy: 'Buy',
    rent: 'Rent',
    addListing: 'Add Listing',
    profile: 'Profile',
    login: 'Login',
    logout: 'Logout',
    contact: 'Contact',
    favorites: 'Favorites',
    admin: 'Admin',
    partnerships: 'Partnerships',

    // Partnerships page
    partnershipsHeroTitle: 'Partner with',
    partnershipsHeroSubtitle: 'Join forces with the leading real estate platform in Albania. Together, we can build the future of property.',
    becomePartner: 'Become a Partner',
    globalReach: 'Global Reach',
    globalReachDesc: 'Access our worldwide network of investors and property seekers.',
    premiumBranding: 'Premium Branding',
    premiumBrandingDesc: 'Align your business with our trusted, high-end real estate platform.',
    growthSupport: 'Growth Support',
    growthSupportDesc: 'Dedicated support team to help you maximize your partnership potential.',
    readyToGrow: 'Ready to grow with us?',
    readyToGrowDesc: 'Let\'s discuss how we can create value together. Contact our partnership team today.',

    // Home page
    heroTitle: 'Find Your Dream Home',
    heroSubtitle: 'Discover premium properties, connect with trusted agents, and find the perfect place to call home.',
    searchPlaceholder: 'Search properties in Albania...',
    searchButton: 'Search',
    whatAreYouLookingFor: 'What are you looking for?',
    selectPropertyPurpose: 'Choose whether you want to buy or rent',
    buyProperty: 'Buy Property',
    rentProperty: 'Rent Property',
    cancel: 'Cancel',
    featuredListings: 'FEATURED LISTINGS',
    promotedProperties: 'Promoted Properties',
    promotedPropertiesDesc: 'Properties promoted by owners for maximum visibility',
    noFeaturedProperties: 'No Featured Properties Yet',
    noFeaturedPropertiesDesc: 'Property owners can promote their listings for free to appear here!',

    // Home page stats and sections
    trustedPlatform: 'Trusted Real Estate Platform in Albania',
    properties: 'Properties',
    happyClients: 'Happy Clients',
    expertAgents: 'Expert Agents',
    viewDetails: 'View Details',
    viewAllProperties: 'View All Properties',
    whyChooseUs: 'Why Choose Us?',
    whyChooseUsSubtitle: 'Your trusted partner in finding the perfect property',
    verifiedListings: 'Verified Listings',
    verifiedListingsDesc: 'All properties are verified and checked by our team for quality assurance.',
    expertAgentsTitle: 'Expert Agents',
    expertAgentsDesc: 'Connect with experienced real estate professionals who know the market.',
    fastAndEasy: 'Fast & Easy',
    fastAndEasyDesc: 'Find your dream home quickly with our advanced search and filtering tools.',

    // Property details
    forSale: 'For Sale',
    forRent: 'For Rent',
    featured: 'FEATURED',
    rooms: 'rooms',
    bathrooms: 'bathrooms',
    size: 'm²',
    contactOwner: 'Contact Owner',
    viewOnMap: 'View on Map',
    description: 'Description',
    location: 'Location',
    price: 'Price',
    type: 'Type',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',

    // Profile page
    profileTitle: 'My Profile',
    myListings: 'My Listings',
    noListings: 'No listings yet',
    noListingsDesc: 'Start adding properties to showcase them here',
    editListing: 'Edit',
    deleteListing: 'Delete',
    promoteForFree: '🚀 Promote for FREE (14 days)',
    featuredListing: '✅ Featured Listing',
    views: 'views',
    profileInformation: 'Profile Information',
    edit: 'Edit',
    email: 'Email',
    phone: 'Phone',
    firstName: 'First Name',
    lastName: 'Last Name',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'Once you delete your account, there is no going back. Please be certain.',
    deleteAccountPermanently: 'Delete My Account Permanently',
    logOut: 'Log Out',
    user: 'User',
    agent: 'Agent',

    // Boost Success Modal
    successTitle: 'Success!',
    listingBoosted: 'Listing Boosted!',
    boostSuccessMessage: 'Your listing has been successfully boosted for 15 days',
    premiumVisibility: 'Premium Visibility',
    boostActiveMessage: 'Your listing will now appear at the top of search results',
    refreshingPage: 'Refreshing page...',

    // Mark as Sold
    markAsSold: 'Mark as Sold',
    markAsSoldTitle: 'Mark as Sold?',
    markAsSoldConfirm: 'This will record the sale in your statistics and remove the listing from the platform. This action cannot be undone.',
    confirmSold: 'Yes, Mark as Sold',
    congratulations: 'Congratulations!',
    propertySold: 'Property Sold Successfully!',
    saleRecorded: '🏆 Sale Recorded!',
    congratsMessage: 'Your sale has been recorded in your statistics. The listing has been removed from the platform.',
    thankYou: 'Thank you for using our platform!',
    keepUpSuccess: 'Keep up the great work! 🚀',
    markSoldError: 'Failed to mark as sold. Please try again.',

    editListingTitle: 'Edit Listing',
    title: 'Title',
    currentImages: 'Current Images',
    newImages: 'New Images',
    addMoreImages: 'Add More Images',
    youCanSelectMultiple: 'You can select multiple images at once',
    expiresSoon: 'Expiring soon',
    daysLeft: 'days left',
    pleaseLogInToViewProfile: 'Please log in to view your profile.',
    loadingProfile: 'Loading profile...',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    passwordMinLength: 'Password must be at least 6 characters',
    updatingPassword: 'Updating password...',
    passwordChangedSuccess: 'Password changed successfully!',
    wrongCurrentPassword: 'Current password is incorrect.',
    cannotChangePasswordGoogle: 'You signed in with Google. Password change is not available for Google accounts.',
    pleaseLoginAgain: 'Please log out and log in again before changing your password.',
    passwordChangeInfo: 'Your new password must be at least 6 characters and different from your current password.',
    promoteYourListing: '🚀 Promote Your Listing',
    getMaxVisibility: 'Get maximum visibility and attract more buyers - completely FREE!',
    featuredListingPlan: '⭐ Featured Listing',
    promoteProperty14Days: 'Promote your property for 14 days at no cost',
    freeLabel: 'FREE',
    days14: '14 days',
    featuredOnHomepage: 'Featured on homepage for maximum visibility',
    topOfSearchResults: 'Top of search results in all categories',
    specialFeaturedBadge: 'Special featured badge on your listing',
    days14Premium: '14 days of premium placement',
    increasedViews: 'Increased views and engagement',
    promotingListing: 'Promoting Listing...',
    completelyFree: 'Completely Free:',
    noPaymentRequired: 'No payment required! Your listing will be automatically promoted for 14 days and appear at the top of search results.',

    // Paid Promotion (€1)
    boostPropertyFor15Days: 'Boost your property for 15 days',
    days15: '15 days',
    days15Premium: '15 days of premium placement',
    payWithCreditCard: 'Pay with Credit/Debit Card - €1',
    payWithCardShort: 'Pay with Credit or Debit Card',
    securePayment: 'Secure Payment',
    securePaymentDesc: 'Pay directly with your credit or debit card. Your listing will be boosted immediately after payment confirmation.',
    securePaymentPoweredBy: 'Secure payment powered by PayPal',
    boostListingButton: 'Boost Listing',

    // ListingPage translations
    exploreProperties: 'Explore Properties',
    findPerfectHome: 'Find your perfect home from {count} available listings',
    search: 'Search',
    searchPlaceholder: 'Search by title or location...',
    type: 'Type',
    all: 'All',
    buy: 'Buy',
    rent: 'Rent',
    propertyType: 'Property Type',
    allTypes: 'All Types',
    apartment: 'Apartment',
    privateHome: 'Private Home',
    land: 'Land',
    business: 'Business',
    priceRange: 'Price Range',
    features: 'Features',
    clearAll: 'Clear All',
    min: 'Min',
    max: 'Max',
    loadingProperties: 'Loading properties...',
    pleaseWaitFetching: 'Please wait while we fetch the listings',
    updatingMap: 'Updating map...',
    filteringResults: 'Filtering results...',
    noPropertiesFound: 'No properties found',
    adjustFilters: 'Try adjusting your filters to see more results',
    forRent: 'For Rent',
    forSale: 'For Sale',
    featured: 'FEATURED',
    showMap: 'Show Map',
    showListings: 'Show Listings',

    // ListingMain translations
    loading: 'Loading...',
    fullView: 'Full view',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    propertySize: 'Property Size',
    location: 'Location',
    listingId: 'Listing ID',
    notSpecified: 'Not specified',
    description: 'Description',
    propertyDetails: 'Property Details',
    listedBy: 'Listed By',
    realEstateAgent: 'Real Estate Agent',
    agency: 'Agency',
    privateSeller: 'Private Seller',
    email: 'Email',
    phone: 'Phone',
    callNow: 'Call Now',
    sendEmail: 'Send Email',
    calculateMortgage: 'Calculate Mortgage',
    hideMortgage: 'Hide Mortgage',
    mortgageCalculatorTitle: 'Mortgage Calculator',
    estimateMonthlyPayment: 'Estimate your monthly payment',
    estimatedMonthlyPayment: 'Estimated Monthly Payment',
    principalAndInterest: 'Principal & Interest',
    propertyPrice: 'Property Price',
    downPayment: 'Down Payment',
    interestRate: 'Interest Rate',
    loanTerm: 'Loan Term',
    years: 'years',
    loanAmount: 'Loan Amount',
    totalPayment: 'Total Payment',
    totalInterest: 'Total Interest',
    mortgageDisclaimer: '* This is an estimate. Actual payments may vary based on taxes, insurance, and other factors.',
    shareProperty: 'Share this property',
    removeFromFavorites: 'Remove from favorites',
    addToFavorites: 'Add to favorites',
    perMonth: 'per month',
    listedOnPlatform: 'Listed on this platform',

    // WhatsApp Messages
    whatsappMessageToSeller: 'Hi! I\'m interested in your property: {title} - €{price}\n\nView here: {link}',
    whatsappShareMessage: 'Check out this property: {title} - €{price} {link}',

    // Time ago translations
    postedAgo: 'Posted',
    justNow: 'Just now',
    oneMinuteAgo: '1 minute ago',
    minutesAgo: 'minutes ago',
    oneHourAgo: '1 hour ago',
    hoursAgo: 'hours ago',
    oneDayAgo: '1 day ago',
    daysAgo: 'days ago',
    oneWeekAgo: '1 week ago',
    weeksAgo: 'weeks ago',
    oneMonthAgo: '1 month ago',
    monthsAgo: 'months ago',
    oneYearAgo: '1 year ago',
    yearsAgo: 'years ago',

    // Map translations
    exactLocation: 'Exact Location',
    staticMapInfo: 'This map shows the approximate location of the property',
    openInMaps: 'Open in Maps',
    clickToOpenMaps: 'Click to open in Google Maps for directions',

    // Contact page translations
    wereHereToHelp: "We're Here to Help",
    getInTouch: 'Get in Touch',
    contactPageSubtitle: 'Have a question or need assistance? Our team is ready to help you find your dream property.',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    visitUs: 'Visit Us',
    mondayToFriday: 'Mon-Fri from 8am to 5pm',
    emailResponse: "We'll respond within 24 hours",
    comeVisitOffice: 'Come say hello at our office',
    sendUsMessage: 'Send Us a Message',
    formSubtitle: 'Fill out the form below and we\'ll get back to you as soon as possible.',
    thankYouMessage: 'Thank you! Your message has been sent successfully.',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    subject: 'Subject',
    selectSubject: 'Select a subject',
    generalInquiry: 'General Inquiry',
    buyingProperty: 'Buying Property',
    sellingProperty: 'Selling Property',
    rentingProperty: 'Renting Property',
    technicalSupport: 'Technical Support',
    other: 'Other',
    message: 'Message',
    messagePlaceholder: 'Tell us how we can help you...',
    sendMessage: 'Send Message',
    officeHours: 'Office Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    commonQuestions: 'Common Questions',
    howToListProperty: 'How do I list my property?',
    listingFees: 'What are the listing fees?',
    howBoostingWorks: 'How does boosting work?',
    officeLocationMap: 'Office Location Map',

    // FAQ Pages - How to List Property
    backToContact: 'Back to Contact',
    howToListTitle: 'How to List Your Property',
    howToListSubtitle: 'Follow these simple steps to list your property on our platform',
    stepAccount: 'Create an Account',
    stepAccountDesc: 'Sign up using email or Google. It\'s quick, easy, and completely free.',
    stepClickAdd: 'Click "Add Listing"',
    stepClickAddDesc: 'Find the button at the top of the page. You must be logged in to add properties.',
    stepFillDetails: 'Fill in the Details',
    stepFillDetailsDesc: 'Add title, description, price, type (For Sale/Rent), number of rooms and bathrooms.',
    stepUploadPhotos: 'Upload Photos',
    stepUploadPhotosDesc: 'Add up to 10 high-quality photos of your property. Good photos attract more buyers!',
    stepAddLocation: 'Add Location',
    stepAddLocationDesc: 'Use format: City, Street (e.g., Tirana, Qemal Stafa Street). Location must be accurate.',
    stepSubmit: 'Submit and Publish',
    stepSubmitDesc: 'Review all details and click Submit. Your property will be visible immediately!',
    quickTips: 'Quick Tips',
    tipQuality: 'Use high-quality photos',
    tipHonest: 'Be honest with description and price',
    tipRespond: 'Respond quickly to interested buyers',
    tipUpdate: 'Keep your listing updated',
    readyToList: 'Ready to List Your Property?',
    startListingNow: 'Start Listing Now',

    // FAQ Pages - Listing Fees
    listingFeesTitle: 'Listing Fees',
    listingFeesSubtitle: 'Transparent pricing. Zero commission.',
    freeListingTitle: 'FREE Basic Listing',
    freeListingSubtitle: 'Free Listing Forever',
    freeFeature1: 'Unlimited Listings',
    freeFeature2: 'Up to 10 Photos per Property',
    freeFeature3: 'Appears in All Searches',
    freeFeature4: 'Contact Forms',
    freeFeature5: 'No Time Limit',
    freeFeature6: '0% Commission',
    freeFeature7: 'No Hidden Fees',
    premiumBoostTitle: 'Premium Boost',
    premiumBoostSubtitle: '€5 for 15 Days',
    premiumFeature1: 'Featured Badge',
    premiumFeature2: 'Top Position',
    premiumFeature3: 'Homepage Priority',
    premiumFeature4: '5x More Views',
    premiumFeature5: 'Instant Activation',
    premiumFeature6: '15 Days Active',
    noCommissionNote: 'No commission is taken on sales. You keep 100% of your profit!',
    getStartedFree: 'Get Started Free',

    // FAQ Pages - How Boosting Works
    howBoostingTitle: 'How Boosting Works',
    howBoostingSubtitle: 'Increase your property visibility with premium boosting',
    whatIsBoost: 'What is Boosting?',
    whatIsBoostDesc: 'Boosting places your property at the top of search results and on the homepage, ensuring maximum visibility to potential buyers. Your property will appear with a special badge and receive 5 times more views.',
    benefit1Title: 'Featured Badge',
    benefit1Desc: 'Stand out with a special badge',
    benefit2Title: 'Top Position',
    benefit2Desc: 'Appears at top of searches',
    benefit3Title: 'Homepage Priority',
    benefit3Desc: 'Shows in featured section',
    benefit4Title: '5x More Views',
    benefit4Desc: 'Increase visibility dramatically',
    benefit5Title: 'Instant Activation',
    benefit5Desc: 'Starts immediately after payment',
    benefit6Title: '15 Days Active',
    benefit6Desc: 'Full coverage for 2 weeks',
    howToBoostTitle: 'How to Boost Your Property',
    howToStep1: 'Go to your profile and find the property you want to boost',
    howToStep2: 'Click the "Boost Property" button',
    howToStep3: 'Choose PayPal as payment method and confirm €5',
    howToStep4: 'Your property is boosted immediately after successful payment!',
    pricingTitle: 'Pricing and Renewal',
    pricingDesc: 'Boosting costs €5 for 15 days. After expiration, your property returns to normal listing. You can re-boost anytime!',
    boostYourProperty: 'Boost Your Property',

    // AddListing page translations
    addNewListing: 'Add New Listing',
    listingType: 'Listing Type',
    forSale: 'For Sale',
    forRent: 'For Rent',
    propertyTitle: 'Property Title',
    locationPlaceholder: 'Location (e.g., Vlore, Lungomare)',
    locationHint: 'Use format: City, Street (e.g., Vlore, Lungomare)',
    locationFormatError: 'Please use format: City, Street (e.g., Vlore, Lungomare)',
    locationNotGeocoded: 'Please wait for the location to be verified or use a different format',
    geocoding: 'Geocoding...',
    pricePlaceholder: 'Price (€)',
    selectPropertyType: 'Select Property Type',
    sizePlaceholder: 'Size (m²)',
    roomsPlaceholder: 'Rooms',
    bathroomsPlaceholder: 'Bathrooms',
    descriptionPlaceholder: 'Description',
    // New apartment/house features
    additionalFeatures: 'Additional Features',
    floor: 'Floor',
    floorPlaceholder: 'Floor (e.g., 3)',
    totalFloors: 'Total Floors',
    totalFloorsPlaceholder: 'Total Floors (e.g., 5)',
    hasElevator: 'Has Elevator',
    hasParking: 'Has Parking',
    hasGarage: 'Has Garage',
    hasBalcony: 'Has Balcony',
    uploadImages: 'Upload Images (Multiple)',
    selectMultipleImages: 'You can select multiple images at once',
    selectedImages: 'Selected Images',
    submitListing: 'Submit Listing',
    mustBeLoggedIn: 'You must be logged in to add a listing.',
    listingAddedSuccessfully: '✅ Listing added successfully!',
    failedToAddListing: '❌ Failed to add listing.',
    errorOccurred: '⚠️ An error occurred while uploading the listing.',
    uploadingListing: 'Uploading Listing...',
    preparingListing: 'Preparing your listing...',
    uploadingImages: 'Uploading images...',
    listingCreatedSuccess: 'Listing created successfully!',
    success: 'Success',
    redirectingToListing: 'Redirecting to your listing...',
    updatingForm: 'Updating form',
    businessPropertyNote: 'Business Property',
    businessPropertyDescription: 'Describe business details in the description (type of business, equipment, etc.)',
    landPropertyNote: 'Land Property',
    landPropertyDescription: 'Specify land size and intended use in the description.',

    // Profile updates
    updatingProfile: 'Updating profile...',
    updatingListing: 'Updating listing...',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileUpdateError: 'Failed to update profile',
    listingUpdatedSuccess: 'Listing updated successfully!',
    listingUpdateError: 'Failed to update listing. Please try again.',
    listingDeletedSuccess: 'Listing deleted successfully!',
    listingDeleteError: 'Failed to delete listing. Please try again.',
    listingBoostedSuccess: 'Listing promoted successfully! It will be featured for 14 days.',
    listingBoostError: 'Failed to boost listing. Please try again.',
    emailVerificationSent: 'A verification link has been sent to your new email. Please verify your new email address to complete the change.',
    emailAlreadyInUse: 'This email is already in use by another account',
    invalidEmail: 'Invalid email address',

    // Auth Handler
    invalidLink: 'Invalid or expired link',
    enterNewPassword: 'Please enter your new password',
    emailVerifiedSuccess: 'Your email has been verified successfully! You can now log in.',
    emailRecoveredSuccess: 'Your email has been recovered successfully!',
    unsupportedAction: 'Unsupported action',
    linkExpired: 'This link has expired. Please request a new one.',
    linkInvalid: 'This link is invalid or has already been used.',
    actionFailed: 'Action failed. Please try again.',
    passwordResetSuccess: 'Your password has been reset successfully! Redirecting to login...',
    passwordResetFailed: 'Failed to reset password. Please try again.',
    redirectingToLogin: 'Redirecting to login...',
    goToLogin: 'Go to Login',
    requestNewLink: 'Request New Link',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',

    success: 'Success!',
    error: 'Error!',
    warning: 'Warning!',
    okay: 'Okay',
    confirmDelete: 'Confirm Delete',
    deleteListingConfirm: 'Are you sure you want to delete this listing? This action cannot be undone.',
    deleteNow: 'Delete Now',
    accountDeletionCancelled: 'Account deletion cancelled.',
    confirmPasswordToDelete: 'Please confirm your password to delete your account:',
    wrongPassword: 'Incorrect password.',
    accountDeletedSuccess: 'Your account has been permanently deleted.',
    accountDeletionError: 'Failed to delete account',
    confirmAccountDeletion: 'Are you absolutely sure you want to delete your account?',
    deletingAccount: 'Deleting...',
    invalidPhoneNumber: 'Please enter a valid phone number with country code',

    // Boost modal
    promoteYourListing: '🚀 Promote Your Listing',
    maxVisibilityDesc: 'Get maximum visibility and attract more buyers - completely FREE!',
    featuredListingPlan: '⭐ Featured Listing',
    promotePropertyDesc: 'Promote your property for 14 days at no cost',
    free: 'FREE',
    days14: '14 days',
    featuredHomepage: 'Featured on homepage for maximum visibility',
    topSearchResults: 'Top of search results in all categories',
    specialBadge: 'Special featured badge on your listing',
    premiumPlacement: '14 days of premium placement',
    increasedViews: 'Increased views and engagement',
    promoteButton: '🚀 Promote for FREE (14 Days)',
    promotingListing: 'Promoting Listing...',
    completelyFree: 'Completely Free:',
    completelyFreeDesc: 'No payment required! Your listing will be automatically promoted for 14 days and appear at the top of search results.',

    // Filters
    allTypes: 'All Types',
    sale: 'Sale',
    rent: 'Rent',
    privateHome: 'Private Home',
    apartment: 'Apartment',
    land: 'Land',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    filters: 'Filters',

    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    submit: 'Submit',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',

    // Footer
    footerTagline: 'Your trusted platform for buying, selling, and renting premium properties across Albania.',
    quickLinks: 'Quick Links',
    buyProperty: 'Buy Property',
    rentProperty: 'Rent Property',
    listYourProperty: 'List Your Property',
    allProperties: 'All Properties',
    resources: 'Resources',
    about: 'About Us',
    howItWorks: 'How It Works',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    contactUs: 'Contact Us',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved.',
    cookiePolicy: 'Cookie Policy',
    termsOfUse: 'Terms of Use',

    // About page
    aboutHeroTitle: 'About Us',
    aboutHeroSubtitle: 'Your trusted partner for real estate solutions in Albania',
    aboutStatsProperties: 'Properties',
    aboutStatsClients: 'Happy Clients',
    aboutStatsAgents: 'Professional Agents',
    aboutStatsYears: 'Years Experience',
    aboutStoryTitle: 'Our Story',
    aboutStoryPara1: 'RealEstateAL was founded with a simple vision: to make buying, selling, and renting properties in Albania easier, more transparent, and accessible for everyone.',
    aboutStoryPara2: 'Since our inception, we\'ve been committed to providing the best possible service to our clients. Our platform connects buyers, sellers, and renters with quality properties across Albania.',
    aboutStoryPara3: 'Today, we\'re proud to be one of Albania\'s leading real estate platforms, helping hundreds of families and businesses find their perfect property every year.',
    aboutValuesTitle: 'Our Values',
    aboutValuesSubtitle: 'The principles that guide everything we do',
    aboutValueTrust: 'Trust',
    aboutValueTrustDesc: 'We build trust through transparency, honesty, and integrity in every transaction. All properties are verified and guaranteed.',
    aboutValueInnovation: 'Innovation',
    aboutValueInnovationDesc: 'We leverage the latest technology, including Google Gemini AI, to provide the best possible experience for our users.',
    aboutValueExcellence: 'Excellence',
    aboutValueExcellenceDesc: 'We strive for excellence in every aspect of our service, from the quality of properties to customer support.',
    aboutTeamTitle: 'Meet Our Team',
    aboutTeamSubtitle: 'The dedicated professionals behind your success',
    aboutTeamCEO: 'Chief Executive',
    aboutTeamCEORole: 'CEO & Founder',
    aboutTeamCTO: 'Technology Director',
    aboutTeamCTORole: 'CTO',
    aboutTeamHead: 'Sales Director',
    aboutTeamHeadRole: 'Head of Sales',
    aboutCTATitle: 'Ready to Find Your Dream Home?',
    aboutCTASubtitle: 'Start your journey today with RealEstateAL',
    aboutCTABrowse: 'Browse Properties',
    aboutCTAContact: 'Contact Us',

    // Messages
    loginRequired: 'Please log in to add a listing.',
    loginToBuy: 'Please log in to contact the owner.',
    addedToFavorites: 'Added to favorites',
    removedFromFavorites: 'Removed from favorites',
    listingDeleted: 'Listing deleted successfully',
    listingUpdated: 'Listing updated successfully',
    boostSuccess: 'Listing boosted successfully! It will be promoted for 14 days.',
    boostError: 'Failed to boost listing',

    // Favorites page
    myFavorites: 'My Favorites',
    savedProperties: 'Saved Properties',
    property: 'Property',
    properties: 'Properties',
    loadingFavorites: 'Loading your favorites...',
    noFavoritesYet: 'No favorites yet',
    startSavingProperties: 'Start saving properties you love by clicking the heart icon',
    browseProperties: 'Browse Properties',

    // Privacy Policy
    privacyPolicyTitle: 'Privacy Policy',
    lastUpdated: 'Last Updated',
    privacyLastUpdated: 'November 3, 2025',
    privacyIntroTitle: 'Introduction',
    privacyIntroText1: 'RealEstateAL ("we", "us", or "our") respects your privacy and is committed to protecting the personal information you share with us. This Privacy Policy explains how we collect, use, store, and protect your information when you use our platform.',
    privacyIntroText2: 'By using our service, you agree to the practices described in this policy.',
    privacyInfoCollectTitle: 'Information We Collect',
    privacyPersonalInfo: 'Personal Information',
    privacyInfoName: 'Name and surname',
    privacyInfoEmail: 'Email address',
    privacyInfoPhone: 'Phone number',
    privacyInfoAddress: 'Address',
    privacyPropertyInfo: 'Property Information',
    privacyInfoPropertyDetails: 'Property details (type, size, price)',
    privacyInfoPhotos: 'Photos and descriptions',
    privacyInfoLocation: 'Location',
    privacyInfoPrice: 'Pricing information',
    privacyUsageData: 'Usage Data',
    privacyInfoBrowser: 'Browser type and version',
    privacyInfoIP: 'IP address',
    privacyInfoPages: 'Pages visited',
    privacyInfoSearches: 'Searches and filters used',
    privacyHowWeUseTitle: 'How We Use Your Information',
    privacyUseProvideServices: 'To provide and maintain our service',
    privacyUseConnect: 'To connect buyers and sellers',
    privacyUseImprove: 'To improve our platform',
    privacyUseSendUpdates: 'To send you requested updates and notifications',
    privacyUseComply: 'To comply with legal obligations',
    privacySharingTitle: 'Information Sharing',
    privacySharingText: 'We may share your information with:',
    privacyShareBuyers: 'Buyers and renters interested in listed properties',
    privacyShareProviders: 'Service providers who help us operate the platform',
    privacySharePayment: 'Payment processors (PayPal) for property boost transactions',
    privacyShareLegal: 'Legal authorities when required by law',
    privacyShareConsent: 'Third parties with your consent',

    // Third-Party Services
    privacyThirdPartyTitle: 'Third-Party Services',
    privacyThirdPartyText: 'We also use trusted third-party services to operate and improve our platform, including Google Analytics (for usage statistics), Firebase (for authentication and data storage), Cloudinary (for image hosting), Google reCAPTCHA (for spam protection), Google Gemini AI (for intelligent assistance), and Mapbox (for interactive maps). These services may collect limited data according to their own privacy policies.',
    privacyThirdPartyAnalytics: 'for usage statistics and traffic analysis',
    privacyThirdPartyFirebase: 'for secure user authentication and data storage',
    privacyThirdPartyCloudinary: 'for property image hosting and optimization',
    privacyThirdPartyRecaptcha: 'for spam and bot protection',
    privacyThirdPartyGemini: 'for AI-powered assistance and chatbot features',
    privacyThirdPartyMapbox: 'for interactive maps and property location visualization',
    privacyThirdPartyNote: 'These services operate under their own privacy policies and may collect information according to their terms.',

    // Payment Processing
    privacyPaymentTitle: 'Payment Processing',
    privacyPaymentText: 'For paid services such as Featured Listing (Boost), we use PayPal to securely process payments.',
    privacyPaymentBoostTitle: 'Boost Listing',
    privacyPaymentBoostText: 'When users pay to promote their listing, the transaction is processed through PayPal. We do not store your credit card details.',
    privacyPaymentInfo1: 'Payment information is securely processed by PayPal',
    privacyPaymentInfo2: 'We only store transaction ID, amount, and status for record-keeping purposes',
    privacyPaymentInfo3: 'PayPal may collect additional information according to their Privacy Policy',
    privacyPaymentInfo4: 'Your payment history is available in your profile',
    privacyPaymentNote: 'Note: We do not have access to your full card details. All payment data is handled by PayPal in accordance with industry standards (PCI DSS).',

    privacySecurityTitle: 'Data Security',
    privacySecurityText: 'We implement reasonable technical and organizational measures to protect your personal information from loss, misuse, unauthorized access, disclosure, alteration, or destruction.',
    privacyCookiesTitle: 'Cookies',
    privacyCookiesText: 'We use cookies to improve your experience. Cookies are small files stored on your device. You can manage cookie preferences through your browser settings.',
    privacyCookieSession: 'Session cookies - for basic functionality',
    privacyCookiePreferences: 'Preference cookies - to remember your preferences',
    privacyCookieAnalytics: 'Analytics cookies - to understand how you use the platform',

    // Data Retention
    privacyRetentionTitle: 'Data Retention',
    privacyRetentionText: 'We retain personal data for as long as necessary to provide services, comply with legal obligations, resolve disputes, and enforce our agreements.',
    privacyRetentionActive: 'Property listings remain active until deleted by the user',
    privacyRetentionInactive: 'Inactive accounts may be deleted after 3 years',
    privacyRetentionLegal: 'Transaction data is retained for 7 years for legal purposes',

    // Legal Basis
    privacyLegalBasisTitle: 'Legal Basis for Processing',
    privacyLegalBasisText: 'We process your personal data based on the following legal grounds:',
    privacyLegalBasisConsent: 'Consent - for marketing emails and promotional communications',
    privacyLegalBasisContract: 'Contract performance - for property transactions and service provision',
    privacyLegalBasisLegitimate: 'Legitimate interest - for service improvement and fraud prevention',
    privacyLegalBasisLegal: 'Legal obligation - for record keeping and reporting',

    // Data Transfers
    privacyDataTransferTitle: 'International Data Transfers',
    privacyDataTransferText: 'Your data may be transferred to and stored on servers located outside Albania, including within the European Union and United States. We ensure that appropriate safeguards are in place to protect your data in accordance with this Privacy Policy.',

    // Enhanced Rights
    privacyRightsIntro: 'Under GDPR and data protection laws, you have the following rights:',
    privacyRightsTitle: 'Your Rights',
    privacyRightAccess: 'Access your personal information',
    privacyRightCorrect: 'Correct inaccurate information',
    privacyRightDelete: 'Request deletion of your information',
    privacyRightObject: 'Object to processing of your information',
    privacyRightExport: 'Export your data in a machine-readable format',
    privacyRightWithdraw: 'Withdraw consent at any time without affecting the lawfulness of processing based on consent before withdrawal',

    privacyOwnershipTitle: 'Website Ownership and Protection',
    privacyOwnershipText1: 'This website, including all of its content, design, code, and features, is the exclusive property of RealEstateAL and is protected by intellectual property laws. Any unauthorized use, reproduction, or distribution is strictly prohibited.',
    privacyOwnershipText2: 'By using this platform, you acknowledge that your use of the service is provided "as is" and "as available". We do not guarantee that the service will be uninterrupted or error-free. Technical bugs may occur and we are continuously working to improve our platform.',
    privacyOwnershipText3: 'Attempts to breach security, hack, or engage in any unauthorized action against our platform will be investigated and prosecuted to the fullest extent of the law.',

    privacyChildrenTitle: 'Children\'s Privacy',
    privacyChildrenText: 'Our service is not intended for persons under 18 years of age. We do not knowingly collect personal information from children.',
    privacyChangesTitle: 'Changes to This Policy',
    privacyChangesText: 'We may update this Privacy Policy periodically. We will notify you of any changes by posting the new policy on this page and updating the "Last Updated" date.',
    privacyContactTitle: 'Contact Us',
    privacyContactText: 'If you have questions about this Privacy Policy, contact us at:',

    // Terms of Service
    termsTitle: 'Terms of Service',
    termsLastUpdated: 'November 3, 2025',
    termsIntroTitle: 'Introduction',
    termsIntroText1: 'Welcome to RealEstateAL! These Terms of Service ("Terms") govern your use of our platform.',
    termsIntroText2: 'Please read these Terms carefully before using our service.',
    termsAcceptanceTitle: 'Acceptance of Terms',
    termsAcceptanceText: 'By accessing or using RealEstateAL, you agree to be bound by these Terms. If you do not agree to any part of these Terms, you may not use our service.',
    termsAccountTitle: 'Account Registration',
    termsAccountText: 'To use some features of our platform, you must create an account. You agree to:',
    termsAccountAccurate: 'Provide accurate and complete information',
    termsAccountSecurity: 'Keep your login credentials secure',
    termsAccountResponsible: 'Be responsible for all activities under your account',
    termsAccountNotify: 'Notify us immediately of any unauthorized use',
    termsListingsTitle: 'Property Listings',
    termsListingsText: 'When posting a property on our platform, you warrant that:',
    termsListingsOwnership: 'You have the legal right to list the property',
    termsListingsAccurate: 'All information provided is accurate and truthful',
    termsListingsLegal: 'The property complies with all legal requirements',
    termsListingsPhotos: 'You have the right to use all photos provided',
    termsListingsProhibited: 'The listing does not contain prohibited or misleading material',
    termsConductTitle: 'User Conduct',
    termsConductText: 'You agree not to:',
    termsConductIllegal: 'Use the platform for illegal purposes',
    termsConductHarmful: 'Post harmful, offensive, or inappropriate content',
    termsConductFraud: 'Engage in fraudulent activities',
    termsConductSpam: 'Send spam or unsolicited messages',
    termsConductInterfere: 'Interfere with the platform\'s operation',
    termsConductInfringe: 'Infringe on others\' intellectual property rights',
    termsFeesTitle: 'Fees and Payments',
    termsFeesText: 'RealEstateAL offers:',
    termsFeesBasic: 'Free basic property listings',
    termsFeesFeatured: 'Paid featured listings (14 days promotion for a fee)',
    termsFeesNonRefundable: 'All fees are non-refundable',
    termsIPTitle: 'Intellectual Property',
    termsIPText1: 'The platform, its content, and materials are owned by RealEstateAL or our licensors. You may not copy, modify, distribute, or use our material without permission.',
    termsIPText2: 'By uploading content, you grant us a non-exclusive, transferable, worldwide license to use, display, and promote your content on our platform.',
    termsDisclaimerTitle: 'Disclaimer of Warranties',
    termsDisclaimerText1: 'THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE". WE MAKE NO WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.',
    termsDisclaimerText2: 'We do not guarantee that the service will be uninterrupted, secure, or error-free. You use the platform at your own risk.',
    termsLiabilityTitle: 'Limitation of Liability',
    termsLiabilityText: 'IN NO EVENT SHALL REALESTATEAL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OR INABILITY TO USE THE PLATFORM.',
    termsIndemnityTitle: 'Indemnification',
    termsIndemnityText: 'You agree to defend, indemnify, and hold harmless RealEstateAL from any claims, damages, losses, or expenses arising from your violation of these Terms.',
    termsTerminationTitle: 'Termination',
    termsTerminationText: 'We reserve the right to suspend or terminate your account and access to the platform at any time, without prior notice, for conduct that violates these Terms.',
    termsGoverningLawTitle: 'Governing Law',
    termsGoverningLawText: 'These Terms are governed by the laws of the Republic of Albania. Any disputes will be resolved in the courts of Tirana.',
    termsChangesTitle: 'Changes to Terms',
    termsChangesText: 'We may update these Terms periodically. Continued use of the platform after changes constitutes your acceptance of the new terms.',
    termsOwnershipTitle: 'Website Ownership and Protection',
    termsOwnershipText1: 'This website, including all of its content, design, code, and features, is the exclusive property of RealEstateAL and is protected by intellectual property laws. Any unauthorized use, reproduction, or distribution is strictly prohibited.',
    termsOwnershipText2: 'By using this platform, you acknowledge that your use of the service is provided "as is" and "as available". We do not guarantee that the service will be uninterrupted or error-free. Technical bugs may occur and we are continuously working to improve our platform.',
    termsOwnershipText3: 'Attempts to breach security, hack, or engage in any unauthorized action against our platform will be investigated and prosecuted to the fullest extent of the law.',
    termsContactTitle: 'Contact Us',
    termsContactText: 'If you have questions about these Terms, contact us at:',

    // Legal page (combined Privacy + Terms)
    legalTitle: 'Legal & Privacy',
    legalSubtitle: 'Privacy Policy and Terms of Service',

    // Login page
    login: 'Login',
    createAccount: 'Create Account',
    firstName: 'First Name',
    lastName: 'Last Name',
    phoneNumber: 'Phone Number',
    person: 'Person',
    agent: 'Agent',
    agency: 'Agency',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    processing: 'Processing...',
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: 'Don\'t have an account?',
    agreeToTermsPart1: 'By signing up, you agree to our',
    and: 'and',
    mustAgreeToTerms: 'You must agree to the Terms of Service and Privacy Policy to continue.',
    resetPassword: 'Reset Password',
    enterEmailReset: 'Enter your email address and we\'ll send you a link to reset your password.',
    emailAddress: 'Email Address',

    // Cookie Consent
    cookieConsentTitle: 'Cookie Notice',
    cookieConsentText: 'We use cookies to improve your experience. By continuing to use this site, you consent to our use of cookies as described in our',
    cookieSettings: 'Settings',
    cookieNecessaryOnly: 'Necessary Only',
    cookieAcceptAll: 'Accept All',
    acceptAll: 'Accept All',
    rejectAll: 'Reject All',
    cookieSettingsTitle: 'Cookie Settings',
    cookieSettingsDescription: 'Choose which types of cookies you want to enable. You can change these settings at any time.',
    necessaryCookies: 'Necessary Cookies',
    necessaryCookiesDesc: 'These cookies are essential for the website to function properly. They cannot be disabled.',
    analyticsCookies: 'Analytics Cookies',
    analyticsCookiesDesc: 'These cookies help us understand how visitors interact with our website.',
    marketingCookies: 'Marketing Cookies',
    marketingCookiesDesc: 'These cookies are used to track visitors across websites for marketing purposes.',
    cookiePreferences: 'Cookie Preferences',
    savePreferences: 'Save Preferences',
    back: 'Back',

    // Consent Management
    consentManagement: 'Consent Management',
    consentManagementDesc: 'Manage your privacy preferences and view your consent history.',
    currentStatus: 'Current Status',
    lastUpdated: 'Last Updated',
    version: 'Version',
    status: 'Status',
    consented: 'Consented',
    withdrawn: 'Withdrawn',
    accepted: 'Accepted',
    rejected: 'Rejected',
    preferencesSaved: 'Preferences saved successfully!',
    errorSavingPreferences: 'Error saving preferences. Please try again.',
    confirmWithdrawConsent: 'Are you sure you want to withdraw your consent? This will set all optional cookies to disabled.',
    consentWithdrawn: 'Consent withdrawn successfully.',
    withdrawConsent: 'Withdraw Consent',
    viewHistory: 'View History',
    consentHistory: 'Consent History',
    saving: 'Saving...',
    cookieNecessaryTitle: 'Necessary Cookies',
    cookieAlwaysActive: 'Always Active',
    cookieNecessaryDescription: 'These cookies are essential for the website to function and cannot be disabled. They include login and saving your preferences.',
    cookieAnalyticsTitle: 'Analytics Cookies',
    cookieAnalyticsDescription: 'These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously.',
    cookieMarketingTitle: 'Marketing Cookies',
    cookieMarketingDescription: 'These cookies are used to display ads that are more relevant to you and your interests. They are also used to limit the number of times you see an ad.',
    cookieSavePreferences: 'Save Preferences',

    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    creatingAccount: 'Creating your account...',
    loggingIn: 'Logging you in...',
    welcome: 'Welcome!',
    hello: 'Hello, {name}!',
    redirectingHome: 'Redirecting to home...',
    passwordsDoNotMatch: 'Passwords do not match!',
    verificationEmailSent: 'Verification email sent! Please check your inbox and verify your email.',
    verifyYourEmail: 'Verify Your Email',
    almostThere: 'Almost there! Just one final step.',
    verificationEmailSentTo: 'We\'ve sent a verification email to:',
    checkInboxAndClickLink: 'Please check your inbox and click the verification link.',
    nextSteps: 'Next Steps',
    openEmailInbox: 'Open your email inbox',
    clickVerificationLink: 'Click the verification link in the email',
    returnAndClickConfirm: 'Return here and click "I Have Verified"',
    iHaveVerified: 'I Have Verified My Email',
    checking: 'Checking...',
    resendEmail: 'Resend Email',
    cancelAndGoBack: 'Cancel and Go Back',
    didntReceiveEmail: 'Didn\'t receive the email?',
    checkSpamFolder: 'Check your spam folder.',
    emailNotVerifiedYet: 'Your email is not verified yet. Please check your inbox and click the verification link.',
    failedToResendEmail: 'Failed to resend email. Please try again.',
    pleaseLoginAgain: 'Please login again to check verification status.',
    pleaseVerifyEmail: 'Please verify your email before logging in. Check your inbox for the verification link.',
    resetEmailSent: 'Reset email sent! Check your inbox.',
    resetEmailError: 'Email not found. Please check and try again.',
    emailNotFound: 'Email not found in our system.',
    invalidEmail: 'The email address is not valid.',
    recaptchaNotReady: 'Security verification is loading. Please try again.',
    recaptchaProtected: 'This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.',
    tooManyAttempts: 'Too many failed attempts. Please wait {seconds} seconds before trying again.',
    loginError: 'Incorrect email or password. {attempts} attempts remaining.',
    accountLocked: '🔒 Account Temporarily Locked',
    waitBeforeRetry: 'Wait {seconds} seconds before trying again.',
    locked: 'Locked',
    emailAlreadyInUse: 'This email is already in use. Please login or use a different email.',
    weakPassword: 'Password is too weak. Please use at least 6 characters.',
    pleaseWait: 'Please wait...',
    joinOurCommunity: 'Join our community today',
    welcomeBack: 'Welcome back! Login to your account',
  }
};

// Language Context
const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  // Default to Albanian (al)
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'al';
  });

  // Save language preference to localStorage
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Get translation function
  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key; // Return key if translation not found
  };

  // Toggle between languages
  const toggleLanguage = () => {
    setLanguage(prev => prev === 'al' ? 'en' : 'al');
  };

  // Set specific language
  const setLang = (lang) => {
    if (lang === 'al' || lang === 'en') {
      setLanguage(lang);
    }
  };

  const value = {
    language,
    setLanguage: setLang,
    toggleLanguage,
    t, // Function for access: t('key')
    isAlbanian: language === 'al',
    isEnglish: language === 'en'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;

